### ISSUE TITLE
New powers/effects and how to implement them

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-game#115]
We've done recent refactoring of active powers, passive powers, effects, etc. This opens up a lot of new possibilities.

It makes sense to start with some practical features we want to actually add to the game now. Working on those may reveal code that needs to be added at the engine level.

Ok, some examples.

### Player-placed traps

I want to add caltrops and bear traps to the game. These will replace the "Immobilize" power in the Ranger tree. The way these work is: use the power to place the trap on the ground. If an enemy moves over them, the trap triggers and the enemy is slowed (caltrops) or immobilized (bear trap) for a short time.

There will be two visuals: one is the placed unsprung trap, and the second is the sprung trap attached to the victim. I think the unsprung trap can be a fixed hazard with a long lifespan, and the sprung trap can be an effect with its own animation.

### Berzerk

I want to add more variety and unique feel to the Minotaurs. Part of what I want to do is give them a Berzerk effect that they gain at half health. Ideally I'd like for it to have multiple status effects. Example:

* Increased damage
* Increased speed
* Decreased avoidance

From what I know about our effect system, each effect only contains one stat right? So to implement this we'd actually need three effects. Maybe one of them (e.g. the increased damage) could come with an animation.

Can active powers (or triggered powers) only create one effect?

Maybe we expand so that either (1) one power can grant multiple effects, (2) one effect can change multiple stats, or (3) both 1 and 2.

Side note: right now effects are kind of like a template, and the actual scalar value is specified elsewhere (e.g. in the activated power). If we expand effects to alter multiple stats it might make the effect interfaces a bit convoluted. I'm actually okay with having effects with fixed scalars. WoW does this with their Spell style effects: there isn't just one Bleeding spell, there are several that represent various bleed damage and durations. But the current system is handy (e.g. where we don't need multiple Bleeds), so if there's a pretty way to expand it then I'd like that.

**Comment by SeaMac** [comment]
Clint and Justin:

Flare is STILL my favorite D&D type game (Trumping "Battle for Wesnoth" 
... ): 3 years later!
I played 2 separate Mage characters through the 10th level - essentially 
completed the original quest twice!

I think the only other game to get this many hours of my life is Py Sol 
Fan Club edition (I'm currently addicted to "Dashavatara Circles" using 
the 10 suit Dashavatara deck from India ... damn. I'm dreaming in these 
silly circles and suits now.).

I am at your disposal to beta test any new content - especially on Mac 
OS 10.9 Mavericks.

Carl
￼<http://softwaresanta.com/sssmf/>
