### ISSUE TITLE
Using units in tooltip texts

### ISSUE THREAD

**Issue by stefanbeller** [clintbellanger/flare-game#239]
Have a look at these images:
![Screenshot from 2013-03-25 00:14:08](https://f.cloud.github.com/assets/455868/296107/cbd34fdc-94d9-11e2-8c41-eae3ecda12ec.png)
![Screenshot from 2013-03-25 00:13:20](https://f.cloud.github.com/assets/455868/296109/cc0e95ba-94d9-11e2-9016-aca6bb83639a.png)
![Screenshot from 2013-03-25 00:14:03](https://f.cloud.github.com/assets/455868/296108/cc0aa072-94d9-11e2-8e6b-e3ce6c0c7ca9.png)

As a non developer it's hard to know what an XP gain by 25 is or MP Regen by 35. We need to put a percentage sign or a "mp/min" there as well

**Comment by dorkster** [comment]
This was fixed in: https://github.com/clintbellanger/flare-engine/commit/1451c92da18c17e3e777c224a479e82995fa4fb3
