### ISSUE TITLE
Double numbers at the action bar: Confusing?

### ISSUE THREAD

**Issue by stefanbeller** [clintbellanger/flare-game#240]
When equipping stackable items at the action bar, the amount of these items is shown, see
the health potion in the image:
![Screenshot from 2013-03-25 00:25:41](https://f.cloud.github.com/assets/455868/296111/3d18ff7a-94da-11e2-9903-71af64ed5844.png)

Having 2 numbers at the health potion might be confusing to the player, specially when being in a stressful combat scene reaching for the required potion.

So we could put a bar there, which indicates if there are "1,2,3 or many" left of these items? Maybe this can be made configurable. This would help to easier see the difference between a number (shortcut key) and a pictogram showing how much item amount is still there.

**Comment by dorkster** [comment]
I've moved the hotkey labels to the slot tooltips: https://github.com/clintbellanger/flare-engine/commit/ca9f50363262596c10d8b27e872e367f42f5136b
It's a much cleaner look and fixes the problem where some hotkey labels were larger than the slots for some translation.

![2015-06-21_231553](https://cloud.githubusercontent.com/assets/913982/8275034/a03b6022-186b-11e5-93e1-4e27ddcef35d.png)
