### ISSUE TITLE
Enemy health bar

### ISSUE THREAD

**Issue by stefanbeller** [clintbellanger/flare-game#241]
When attacking an enemy in a crowd of enemies, you probably want to see the exact enemy you're attacking and not some random hovered enemy. This often happens if you do not aim with the mouse at the actual enemy, but rather just indicate the direction in which the hero is going to put hits.

**Comment by dorkster** [comment]
This was fixed, then broken, and [fixed again](https://github.com/clintbellanger/flare-engine/commit/8107853e71bd99331b623633d7c1c05c97d64676). All should be well now, and this issue can be closed.
