### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-game#298]
It could be beneficial for us to give flare-game a real name.

I have the name Wandercall earmarked for a future project, but it could easily become the name for this one -- and my future project be Wandercall 2.

If we did this, what would be affected?

Flare v0.19 would be strictly the engine. Wandercall v0.19 (or 0.1?) would be strictly the Act I of the beta game. This name separation would, in the long term, make packaging and distribution more clear.

Wandercall would be released with the fantasycore data set so that other people could build campaigns in the Wandercall world.

I would rename the github flare-game repo to wandercall.

I would probably keep flarerpg.org as the engine's website. The "rpg" part at least gives a hint at what flare is about. The look and feel of the Flare site would be simplified to a game-neutral design. The blog archive containing combined engine + game development would remain there. We would feature Wandercall and Polymorphable both with high prominence.

I'd launch a new game site at wandercall.com (I already have the domain). This one would match the fantasy look and feel of the game.

Because we're introducing new beta content with v0.19, this is the best time to do this if we ever will. The new content will come with an official name. Short term there would be some confusion, but long term the separation would make much more sense to everyone.

Please discuss.

**Comment by dorkster** [comment]
Going to close this. Wandercall can be it's own thing. If the Empyrean campaign gets renamed, I think I'm going to go with "Return to Empyrean".
