### ISSUE TITLE
More map transition sounds

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-game#30]
I really like the double doors sound effect when passing between dungeon maps.

We could use a couple more:

* Walking up/down stairs
* Teleport sound (probably not the same as the teleport spell)

**Comment by dorkster** [comment]
Teleporter and stair sounds have been added and used in alpha_demo, empyrean_campaign, and devlab. See the following commits:

* 738de687b2d907936afd7dcc07669e83d0326de1
* e93e8570604aa4cd1a28a016bcc0a5550f7148b1
