### ISSUE TITLE
Ctrl-click sells inventory items without shop attached

### ISSUE THREAD

**Issue by ChrisOelmueller** [clintbellanger/flare-game#34]
I'm not sure this is a bug at all, but if it isn't, the interface should be more clear.

* Open inventory without talking to a merchant, e.g. I
* Ctrl-click on item will add its value to the gold amount and remove the item

I have no idea, however, where the item went and where/whether i can buy it back.

If this is considered a bug, i'd recommend to have ctrl-click drop items instead of selling them unless there's an actual shop or stash to move the item to.

**Comment by dorkster** [comment]
I'm going to close this, since I don't see anything changing in the near future. We already:

- Send insta-sell items to the Buyback stock for vendors.
- Have an engine setting to disable this feature for mods that don't want to use it.
