### ISSUE TITLE
on providing flare-engine and flare-game separately

### ISSUE THREAD

**Issue by hasufell** [clintbellanger/flare-game#344]
You advertise that we packagers should do that, but I don't find flare-game and flare-engine tarballs on sourceforge. The one that is available there includes both parts, without an option to turn off either of those.

So you should either provide a cmake option for installing data-only or provide separate tarballs with separate CMakeLists.txt files. (pulling the flare-game repo from github is not acceptable, because it has almost 300mb overhead due to git history)

Also, the 0.18 tag on the flare-engine repo seems a bit dirty, the CMakeLists.txt still shows 0.17 and does not include some fixes present in the sourceforge tarball.

**Comment by sudoman** [comment]
cmake can auto-generate tarballs:

````
cpack -G TGZ .
````

I'm not sure how flexible that is. I also think you'll need to define the project name in a cmake config file.
