### ISSUE TITLE
Ranged weapon sound effect

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-game#378]
Personally, I've never liked the sound effect we use for slingshots and bows. Ideally, the sound would be the "thwang" caused by the release of tension followed by the "whoosh" of the actual projectile.

I couldn't find anything exactly like that when searching on OpenGameArt and Freesound. So we might need to commission it if it's something we want.

**Comment by dorkster** [comment]
So I found some sound effects that I overlooked on OGA that work well together. Here's a video of the result: https://www.youtube.com/watch?v=6LWKSZpSvt8&feature=youtu.be

Sound effects used:
- http://opengameart.org/content/swish-bamboo-stick-weapon-swhoshes
- http://opengameart.org/content/arrow-hit-twang
- http://opengameart.org/content/wood-wobbling-rattling

**Comment by pennomi** [comment]
These feel much more natural than the old effect. Awesome!

**Comment by clintbellanger** [comment]
fantastic! I approve. Also, some day soon we'll have these in the public domain:

https://www.kickstarter.com/projects/bjjaszcz/the-medieval-weapons-sound-effects-library

That will let us replace lots more sounds, and possibly add in new sound options.

**Comment by dorkster** [comment]
I've pushed the new sounds upstream and updated the [credits page](https://github.com/clintbellanger/flare-game/wiki/Credits#sound-effects) (search for "qubodup").
