### ISSUE TITLE
Design Guide (rough draft) discussion

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-game#395]
I created and will maintain a Design Guide for this game. You can find it [in the wiki](https://github.com/clintbellanger/flare-game/wiki/Codename-Empyrean-design-guide).

Please have a read. It's still a very high level document. We may end up having a document of that size for every aspect of the game (map design, sound design, dialog design).

Please ask questions. And please let me know if you're interested in producing content for the full release.

**Comment by dorkster** [comment]
All quests and mapping for the Empyrean campaign are complete.
