### ISSUE TITLE
Main route map planning

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-game#399]
I created this World Layout wiki page: https://github.com/clintbellanger/flare-game/wiki/World-Layout -- it contains ideas for more maps along the main quest. Please read it first then come back here.

The first few maps are in the current empyrean-campaign mod. I'm working on the beginning maps to set the tone/pace for the rest of the Act.

There are lots of blank maps in there still. This issue is for planning those required maps.

Pitch map ideas below. Especially explain why the map is an interesting use of the tile set. 

The goal is to create a rough description of each map.
- Proposed name
- Which tile set it uses
- Its general layout (maybe including a sketch)
- What special events might be on the map
- What type of creatures are on the map

Some complex map ideas might be reused as side quests or added to the main temples. I'll be strict about content and tone, so be open to suggestions please.

We'll close this ticket when the list of main maps in the World Layout wiki is complete -- that is, each map along the main route has a name and general plan. From there I'll create new milestone/issues to create each map and assign them to volunteers.

**Comment by dorkster** [comment]
As of dadd634cd219e69863b783124cbeb1954d32b76f, mapping for Empyrean is complete! The only exception is the Halls of Infinity maps, which will be re-purposed alpha_demo maps, so not much design work there.
