### ISSUE TITLE
Implement player weapon attack speeds by defining separate animations

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-game#453]
Idea: is it possible to implement different attack speeds by using multiple animations?

Example, in flare-game/fantasycore we have a 4-frame melee "swing" that lasts 400ms. We could make that the "medium swing", and add an additional 300ms fast swing and 500ms slow swing. Same frames of animation, just different speed.

**Comment by dorkster** [comment]
This can be done pretty simply now on the item level:

```
# 200% attack speed
bonus=attack_speed,200
```

To only affect certain animations (e.g. you want to affect physical attacks and not magic cast speed), create a separate effect like so:

```
# powers/effects.txt
[effect]
id=swing_speed
type=attack_speed
can_stack=true
# only affect the swing animation
attack_speed_anim=swing
```
