### ISSUE TITLE
Add new snowplains tileset to fantasycore

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-game#459]
http://opengameart.org/content/isometric-snow-tileset-flare

How about this? @clintbellanger @dorkster @pennomi . It have few issues, which will be fixed soon. Tiled support also present.

Also we could add desert tileset, from here https://github.com/igorko/flare-mod-noname/blob/master/new_game_mod/images/tilesets/tileset_desert.png

**Comment by dorkster** [comment]
The [Empyrean campaign map layout](https://github.com/clintbellanger/flare-game/wiki/World-Layout) mentions some mountain areas, which I think the snow tileset would be perfect for. I really like how they made the ground tiles match with the tops of walls, to give the illusion of multiple tiers.

I'm not sure if the desert tileset fits in anywhere. I don't think it differentiates itself enough from the grassland tileset. Also, I'd like our tilesets to have different overall colors: grassland is green; dungeon is dark grey; cave is brown, snow is white. The desert tileset would be another brown tileset.

**Comment by igorko** [comment]
Can someone look into snowplains in noname-mod repo and fix tileset definitions? I have added all tiles but there can be issues with tile positions.(especially in _ice and_other)  And maybe they should be fixed in both txt and png file. I didn't test _ice and _other parts, but added test map in tiled folder, which can be extended for testing.

**Comment by igorko** [comment]
Snowplains tileset should be ready and can be taken from noname repo. Please get it for testing and map creation, if no more issues will be found, we can merge it into flare-game (better with new snowy maps added)

**Comment by igorko** [comment]
Can we add it, any issues found?

**Comment by dorkster** [comment]
I did a very brief test with the snow tileset a while ago to make sure it worked. I didn't notice any bugs then.

I'll add the snow tileset to this repo when I eventually make a map that uses it.

**Comment by dorkster** [comment]
The snow tileset is now in the empyrean_campaign ([here](https://github.com/clintbellanger/flare-game/blob/master/mods/empyrean_campaign/images/tilesets/tileset_snowplains.png)). There were a few [issues with gaps between the lighter background tiles](https://github.com/clintbellanger/flare-game/commit/7249e85d40348e508a13b66ec23409df436af26f), but I fixed them in GIMP. There were also a few problems with the offsets in the tileset definition ([1](https://github.com/clintbellanger/flare-game/commit/ad389e9f0e0886afefc35c8bc0ff71d7d2d6162c), [2](https://github.com/clintbellanger/flare-game/commit/58bd8cd225438092717a67b725b901e9a3cba919)).

As for attribution, I've added rubberduck to the appropriate parts of the credits, but I have a question. @clintbellanger's temple entrance model is tri-licensed as CC-BY-SA 3.0, GPL 3.0, and GPL 2.0. Does that mean we need to include rubberduck's modified version in `art_src`? I'm not 100% confident how GPL applies to non-code creations.

Anyway, I encourage everyone to take a look at the Lake Kuuma map to see it in action (and check for any oddities). Then we can decide if it can be moved to fantasycore for use everywhere

**Comment by clintbellanger** [comment]
My thoughts -- GPL is largely about source code specifically, which art doesn't technically have. I wouldn't mind if we included such contributed assets in art_src, but it's not required.

I think if the data exists somewhere else in its main form (e.g. on OpenGameArt) then it's okay if our repo only includes the parts we're using (the 2D tiles).

**Comment by igorko** [comment]
we can put sources into art_src directory. but I guess that will need making sources up-to-date, because there were some fixes applied to resulting tileset files

Also I have question to @clintbellanger, do we have (or can someone make) script for auto generating tilesets from blender files. This would be very cool for adding dynamic lights (to generate other versions of textures) and also would speed-up regenerating tiliset if some changes are made to original (also it would be a nice example how to do tilesets in future)
