### ISSUE TITLE
XP doesn't increase in Empyrean Campaign

### ISSUE THREAD

**Issue by Dr-Terrible** [clintbellanger/flare-game#467]
I have upgraded _flare-game_ to 8d6c3ef9f865852541eec9bb007c225bcdbd74e7, and _flare-engine_ to ca9f50363262596c10d8b27e872e367f42f5136b, but killing enemies doesn't increase my XP anymore when playing the _Empyrean Campaign_ — thus preventing me to level up. Instead, it works as expected when playing the _Alpha Demo_.

p.s.: I have removed all my configuration files too (in ~/.local/share/flare and ~/.config/flare), but the issue persists.

**Comment by dorkster** [comment]
Sorry about that. I have been actively working on the Empyrean Campaign, and I disabled enemy XP when trying to balance some of the combat numbers. I'll re-enable them.

**Comment by dorkster** [comment]
Fixed: https://github.com/clintbellanger/flare-game/commit/872d52fcc7891521bc2fb40e40ca12da61cd2021

**Comment by Dr-Terrible** [comment]
Thank you @dorkster !
I can confirm that the issue is gone in 872d52f.
Keep up with the good work guys.
