### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by TaiVuong** [clintbellanger/flare-game#475]
I think that should make transparent icon background instead of black.

**Comment by igorko** [comment]
What icon are you talking about? Can you explain the issue? Desktop icon or window/in-game icon? What platform? Windows , Linux or Android?

**Comment by TaiVuong** [comment]
https://github.com/clintbellanger/flare-game/blob/master/art_src/icons/icons.xcf

**Comment by clintbellanger** [comment]
I like the black background.

**Comment by dorkster** [comment]
I also think that the black background is better. In fact, there is a [duplicate issue](https://github.com/clintbellanger/flare-game/issues/358) where I state the reasoning for my preference.
