### ISSUE TITLE
Please support procedural level generation

### ISSUE THREAD

**Issue by mquinson** [clintbellanger/flare-game#477]
I seem to remember that the issue of random level generation was already discussed somewhere on flare, but I cannot find where, sorry. I just stumbled on that blog issue, and I am wondering of whether it could be adaptable to flare somehow.

http://blog.runevision.com/2015/08/procedural-world-potentials-simulation.html

Thanks for this great game,
Mt

**Comment by igorko** [comment]
There is a repo for map generator here https://github.com/Paul-Wortmann/Random_Map_Generator and it is able to generate maps (build its ui and try), but it's far from complete so its algorithms can't be integrated into game. Also there is no progress some time.

**Comment by igorko** [comment]
Corresponding issue in next generation of engine which could have this feature https://github.com/dorkster/flare-engine-next/issues/23

**Comment by mquinson** [comment]
Thanks for the pointer and sorry for the noise.
