### ISSUE TITLE
Last build error

### ISSUE THREAD

**Issue by TaiVuong** [clintbellanger/flare-game#479]
Force close if i add fantasycore + empyrean_campaign and click play.

OSX 10.10.5
SDL 2.0.3
Log: /Users/.../Git/flare-engine/Launch Flare OSX.command: line 3:  9569 Segmentation fault: 11  ./flare
logout

**Comment by igorko** [comment]
Can you provide more explanation? What version of engine (commit)? How you was adding mods? When game was closed or stared? "click play" on main screen, or create\load game screen?

**Comment by TaiVuong** [comment]
1. git clone https://github.com/clintbellanger/flare-engine.git
2. git clone https://github.com/clintbellanger/flare-game.git
3. brew update, cmake, make
4. copy fantasycore, empyrean_campaign --> flare-engine/mods/
5. delete .local, .config (old version)
6. run Launch Flare OSX.command
7. configuration--> enable fantasycore, empyrean_campaign --> back to title
8. click "Play game" or "configuration'' --> force close

Images before I press the button:
![screen shot 2015-10-19 at 21 24 49](https://cloud.githubusercontent.com/assets/12879647/10580604/71da4446-76a8-11e5-8089-8c4aedd3b516.png)

**Comment by dorkster** [comment]
The black background on the logo/buttons makes me think that maybe there's an issue with the software renderer on OSX. Try running with the hardware renderer:
```
./flare --renderer=sdl_hardware
```

**Comment by TaiVuong** [comment]
@dorkster  ./flare --renderer=sdl_hardware
2015-10-19 22:09:25.397 flare[587:26689] ERROR: SDLHardwareRenderDevice: [images/menus/buttons/button_default.png] Couldn't load button image: Invalid renderer

**Comment by igorko** [comment]
Maybe the problem is in SDL libs, as I see from logs there are two versions installed, in Framework and with homebrew. And OS X wonders what of them to use. Can you move temporarily SDL2.Framework folder to different location and try once again?

**Comment by igorko** [comment]
SDLHardwareRenderDevice can require video drivers I guess to work properly...

**Comment by TaiVuong** [comment]
It's ok now :)

Delete all SDL in Framework + delete "CMakeFiles" in flare-engine then remake.
