### ISSUE TITLE
Can we use the art assets?

### ISSUE THREAD

**Issue by McFarts** [clintbellanger/flare-game#481]
If we give appropriate attribution? If so, what should the attribution be? Thanks!

**Comment by dorkster** [comment]
Take a look at the [Credits wiki page](https://github.com/clintbellanger/flare-game/wiki/Credits) to see how we give attribution.

If there's a specific asset you want to use and you're unclear who to attribute it to, feel free to ask. We'll be able to answer that for you.

**Comment by McFarts** [comment]
Thanks for the fast response~
