### ISSUE TITLE
Android Audio sampling rate

### ISSUE THREAD

**Issue by TaiVuong** [clintbellanger/flare-game#484]
```
sampleRateInHz: the sample rate expressed in Hertz. 44100Hz is currently the only rate that is guaranteed to work on all devices
```
http://stackoverflow.com/questions/7023821/how-to-set-audio-sampling-rate-higher-than-44-1khz-on-linux-android-platform

mods/fantasycore/soundfx/inventory/inventory_book.ogg : 88.2 khz
mods/fantasycore/soundfx/powers/potion.ogg : 88.2 khz
mods/fantasycore/soundfx/powers/shock.ogg : 88.2 khz
mods/fantasycore/soundfx/powers/thunder.ogg : 48 khz (ok)

**Comment by igorko** [comment]
nice catch, looks lik we will need to convert some of the sounds

**Comment by dorkster** [comment]
Actually, these sounds are a higher quality than the engine will even play back on any platform. In the engine, we initialize SDL_Mixer like so:

```
Mix_OpenAudio(22050, AUDIO_S16SYS, 2, 1024)
```

So whenever we load a sound, it gets converted to a sample rate of 22050Hz.

**Comment by TaiVuong** [comment]
just 4 files above.
