### ISSUE TITLE
License violation by another project?

### ISSUE THREAD

**Issue by poVoq** [clintbellanger/flare-game#485]
Came accross this:

https://play.google.com/store/apps/details?id=net.fdgames.ek.android

http://www.exiledkingdoms.com/

Which clearly uses FLARE assets. Nothing wrong with that per se, but I looked a bit around and I couldn't find attribution or a download link for modified art assets as by the SA requirement... or did I miss something?

(Posting here because the FLARE forum on OGA is having some strage issues :( )

**Comment by dorkster** [comment]
Thanks for shining light on this. Definitely looks like a violation of CC-BY SA 3.0's attribution clause. Paging @clintbellanger

**Comment by johndh** [comment]
I looked around a bit, since I saw my orcs in the preview video, and found this:
http://exiledkingdoms.com/ek_credits.html

**Comment by poVoq** [comment]
Ahh, that is pretty well hidden, how did you come across it? I can't see a link to it anywhere.

Seems fine though, so I am closing this.

**Comment by johndh** [comment]
@poVoq It's in the News and Announcements section.  There's also a link to it in the "credits" section of the game's main menu.

**Comment by igorko** [comment]
I have tried the gsme, and to be honest, I like it. It reminds me Gothic, and looks more dynamic then all flare games(sorry). Music is great, there is a lot of interacting with NPCs and the world (well this can be done with flare too). But some things flare doesn't have, which makes me sad. Moving NPCs, party with NPC,  dialogs with NPCs, that propose you different answers, I really like this stuff.

**Comment by igorko** [comment]
More features discovered: dynamic lights, day/night time (and timer), half-transparent walls when avatar is behind them. Well, most of these features are in our wishlist, but have very low priority...
