### ISSUE TITLE
Commission - Weapon expansion

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-game#489]
The project Exiled Kingdoms uses lots of Flare assets. They've donated to Flare in the past in thanks.

David send me a new commission to add some weapons to the Flare fantasycore set. Mainly a variety of axes and hammers, and other weapons with more of a historical/accurate feel.

**Comment by clintbellanger** [comment]
Here is a preview of the new weapons that will be added to fantasycore:

![weapons_sample](https://cloud.githubusercontent.com/assets/689593/13534591/8411492a-e1fb-11e5-9a6d-3cb5a9ae2f70.png)

I'll be creating the sprite sheets and uploading art sources soon.

**Comment by clintbellanger** [comment]
Unpacked sprite sheets and blender sources added to art_src/hero and /heroine in 4a7d3d6b08cfab64d682eadd3d027c5bcb011c6f

**Comment by dorkster** [comment]
Idea: I think we could use some of these for some rare unique items, one for each class...

- Sledgehammer (Brute); Different from our default selection of blades and appears to require the most amount of "strength" to use.
- Small or medium woodcutter's axe (Scout); An "outdoorsman" aesthetic that fits our ranged class. Replaces the rock/arrow animation with our thrown axe animation. Rapid Fire becomes "throw 5 axes at a foe", and that's cool.
- Enchanted mace (Adept); Definitely what I think of when I think "Battle Mage". It's wand-like shape makes this a simple replacement.

**Comment by pennomi** [comment]
Great idea. Was about to suggest something like that.
