### ISSUE TITLE
Max Texture Size

### ISSUE THREAD

**Issue by TaiVuong** [clintbellanger/flare-game#495]
Generally, most modern computers allow for at least 4096x4096 textures, but if you want to be really safe, you can limit to 2048x2048. If you are targeting Android, iOS, or another OpenGL ES device, you might be safer sticking with 1024x1024.

**Comment by igorko** [comment]
Related to https://github.com/dorkster/flare-engine-next/issues/4

**Comment by TaiVuong** [comment]
how to create "../animations/enemies/antlion.txt" ? if you intend to use something as https://www.codeandweb.com/texturepacker, i can help u build a free tool.

**Comment by dorkster** [comment]
We already have a tool for packing sprites: https://github.com/dorkster/RectangleBinPack/tree/fixes

When using that tool, the txt animation files should be in the unpacked format as outlined [here](https://github.com/clintbellanger/flare-engine/wiki/Animation-Definitions).

Our main issue is that even when packed, some spritesheets are too large (see wyvern_adult.png). We need a way to split these into separate files per animation.

**Comment by TaiVuong** [comment]
Where can i find the file with 
```
[stance]
position=0
frames=4
duration=4
type=back_forth
```
I just finish my tool and i want repack some files to test but i have problem with ["animations/enemies/zombie.txt"](https://github.com/clintbellanger/flare-game/blob/master/mods/fantasycore/animations/enemies/zombie.txt), it has two duplicate actions ("shoot", "cast")

**Comment by dorkster** [comment]
Here's an unpacked version of the zombie animation definition: https://gist.github.com/dorkster/c7a8a13cebbf9104c8e5

Don't worry about duplicate actions. The packer should ignore them. In the case that it doesn't, you can simply comment them out with **#**. If you do that, remember to re-add those actions to the packed animation definition.

**Comment by TaiVuong** [comment]
I just finish my tool. u can test it now.
- open .blend run script then new folder "wyvern/raw" will create with "00001.png", "70001.png"... (i rewrited the script to export all Action)
- open java tool
- click "In" button link to folder wyvern --> pack (remove "wyvern/pack" folder if tool dont repack)
- switch to tab "Flare animation" click load ( "wyvern/config.txt") --> export 
--> wyvern/pack/1/ is fantasycore
--> wyvern/pack/.5/ is minicore
- Files: 
[wyvern.zip](https://github.com/clintbellanger/flare-game/files/157278/wyvern.zip)
[TexturePacker-GUI.jar.zip](https://github.com/clintbellanger/flare-game/files/157282/TexturePacker-GUI.jar.zip)
P.S: Can i run Flare without Visual Studio?
