### ISSUE TITLE
TODO: Include unpacked versions of animations in art_src/

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-game#497]
Having these would make it easier for developers to repack sprites after making changes. As far as I know, most of these are not even in the git history of this repo. Luckily, they *are* in the old Flare repo history, but some of their syntax needs to be updated.

**Comment by igorko** [comment]
We should apply this commit fec28e9ac17b8c37409fc984a15d05c6f3615d66 to art_src too, but without packing.

**Comment by dorkster** [comment]
It appears that only the peasants had the old hard shadows in their unpacked versions. I've updated them accordingly.
