### ISSUE TITLE
Add new melee weapons to the game

### ISSUE THREAD

**Issue by clintbellanger** [clintbellanger/flare-game#500]
See the ten new melee weapons added in #489 

What's needed to add these to the game, minimally:
- Create the unpacked animation definition files
- Pack the sprite sheets (and generate packed animation files)
- Add new melee weapons to items.txt

Ideally, we also want to add these:
- ~~Render raw references for icons~~ (clint)
- Paint final icons
- Unique flying loot drop animations
- Add the items to the game content (vendors, treasure, drops, rewards)

Anything else needed, please mention it below. Also, if you want to claim one of these tasks, do so below or start a new Issue if it's gonna get complex. Thanks!

**Comment by clintbellanger** [comment]
Note: these new melee weapons no longer have four frames for the Shoot animation. This was usually for showing the melee weapon stowed away (at the side, or on the back). I think that choice didn't turn out so great, and simply making the melee weapon invisible would work better. So these frames are 1-28, with the Shoot frames 29-32 omitted.

This decision also makes the source Blender files less complicated (how to put the weapon in a different position on certain frames? I was doing it manually before).

I'll make the reference renders for the icons.

**Comment by dorkster** [comment]
First off, the new weapons look great.

I am, however, a bit concerned about the implications of including them in the game. The weapon progression has so far been designed under the assumption that there are three classes, each with their own weapon type. Since all of these weapons are melee-only, we'd have to shift things so that most weapons are viable for all builds.

But let's take a step back and pretend we only have a melee class. How do these weapons fit into *that* progression. What's the gameplay difference between a mace and a shortsword? Are the stats different, or are we just introducing variety for the sake of variety?

The new art definitely belongs in fantasycore for use in many games. I'm just not sure that they should be in the game that *we're* making.

**Comment by clintbellanger** [comment]
Understandable, if the campaign design is far enough along then these could be hard to fit in. Don't let it delay the work going on.

At least, keep them in mind with new content going forward.

**Comment by dorkster** [comment]
Idea: I think we could use some of these for some rare unique items, one for each class...

- Sledgehammer (Brute); Different from our default selection of blades and appears to require the most amount of "strength" to use.
- Small or medium woodcutter's axe (Scout); An "outdoorsman" aesthetic that fits our ranged class. Replaces the rock/arrow animation with our thrown axe animation. Rapid Fire becomes "throw 5 axes at a foe", and that's cool.
- Enchanted mace (Adept); Definitely what I think of when I think "Battle Mage". It's wand-like shape makes this a simple replacement.

**Comment by McSinyx** [comment]
I have an idea too. Let those weapon be picked up and only picked up from enemies and the picking up chance to be small. That won't break the game's class-balancing and logic.

**Comment by dorkster** [comment]
>I have an idea too. Let those weapon be picked up and only picked up from enemies and the picking up chance to be small. That won't break the game's class-balancing and logic.

That's exactly what I was getting at when I said "rare unique" in my previous post. Such items are dropped by mini-bosses and bosses at a low rate.

**Comment by clintbellanger** [comment]
I created renders for icons. They may be good enough to use in game as-is, but I've also added 256x256 px renders of the icons for later paint-over.

Here's how they look now, compared to the other weapons.

![image](https://cloud.githubusercontent.com/assets/689593/13754066/a2d3e2c4-e9e3-11e5-9df9-9d7d3f20df4f.png)

**Comment by dorkster** [comment]
I've added the weapons to fantasycore: https://github.com/clintbellanger/flare-game/commit/c13a809e1bad6fea71ad476016496bad572b2f1d

All we need now is flying loot animations.

**Comment by dorkster** [comment]
Flying loot animations are done!: https://github.com/clintbellanger/flare-game/commit/e4f8120a66b2bd64550c011ab22e5ef8a8787362

Preview:
![weapons](https://cloud.githubusercontent.com/assets/913982/18040791/bc1b64d0-6d7f-11e6-9e5c-350c4f855f2e.gif)

**Comment by DoKel** [comment]
As I can see, now all weapons have same attack speed (meant, that delay between two attacks). The idea is to do it different for different types of weapons, i.e. abstract sword can have X damage and 1 attack every Y seconds speed, when abstarct axe can have 2*X damage and 1 attack every Y*2 seconds speed. So, choosing different types of weapons would perfectly fit into progress model, and will have difference in gameplay too.

**Comment by dorkster** [comment]
For empyrean_campaign, we'll keep all the base weapon speeds the same. However, as mentioned in #453, we have an easy way to modify attack speeds for items.

Closing this because the original issue (get the new items in the game) has been completed.
