### ISSUE TITLE
Allow character to raise daemon 

### ISSUE THREAD

**Issue by chlin501** [clintbellanger/flare-game#501]
This feature basically is like necromancer allowing the player/ character create pet-like creatures, which would help attack enemies in game.

**Comment by igorko** [comment]
We support this on engine level, but currently developed game doesn't use all engine features.  @dorkster does current game layout allow to have such thing?

**Comment by dorkster** [comment]
The Empyrean campaign uses consumable scrolls as a way to summon creatures. Currently, there is only a Summon Zombie scroll available for sale from Bakat in Lake Kuuma. There will be more eventually.

**Comment by chlin501** [comment]
Sorry didn't know that, and thanks for the explanation!
