### ISSUE TITLE
36k of gold on latest map

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-game#510]
Maybe it should be rebalansed? I think it's too much of free gold. I'm on 11 level, I have sold a lot of found stuff, my stash is almost full, and I don't need to buy something because I already have a lot of stuff that can't use because requirements are not met.

**Comment by dorkster** [comment]
I don't mind players having a surplus of gold. There are three main factors in play here:

- Luck. Players might not find much stuff to sell or piles of gold.
- Skill level. Some players might be spending more on potions if they're having a difficult time.
- Gear. Players might use equipment that increases the amount of gold found, such as rings and some unique gear. Luck could partially play into this, as these items might not drop/show up for sale.

Overall, I've balanced for a worst-case scenario player. I'd rather a best-case scenario player feel unchallenged than a worst-case scenario player feel frustrated.

**Comment by Pawonashi** [comment]
On PC I'm in similar situation - I have 20k spare gold with 12lvl brute, I have one item in the Stash (a unique bow), every new level I visit Abasi on Nazia Highlands to buy some new cool stuff.

On the other hand, I have 10lvl female Adept on Android and I have only 10k gold (i was storing it in the stash in case of death) and from time to time i have to buy some new potions or new armor. Now she's crossed the sewers in Black Oak Farm and she can rest for now, but I don't think that I have too much gold in that case.
