### ISSUE TITLE
Ranged enemies want to be killed

### ISSUE THREAD

**Issue by DoKel** [clintbellanger/flare-game#518]
In game, I can see, that all enemies are going straight to the hero, when they meet him. And so ranged enemies do that too. I can't find logical explanation for that behaviour --- if they can damage player, and not be damaged, what's the reason, to go to player closer? I thought, maybe their melee attacks are greater, than ranged, but, fro example, at lvl3_skeleton_sniper.txt I can see following:

stat=dmg_melee_min,35
stat=dmg_melee_max,40
stat=dmg_ranged_min,45
stat=dmg_ranged_max,50

So, melee damage for them are reduced (in comare with ranged). I think that have to be fixed, and I see two possible ways:

1. Just amplify melee damage
2. Let ranged enemies just stand there they are. Possibly, they have to follow player, if he is running out of their attack range. Maybe they also have to run from player for sayving their life, like minotaur_necromancer does.

**Comment by clintbellanger** [comment]
This is all easily tweakable. This line controls that behavior:

    chance_pursue=5

Unless the implementation has changed, this means every frame this enemy is just standing around it has a 5% change of starting to move towards the player. 5% is quite high per frame, that means the sniper is likely to pursue after only a second (5% chance, and 30 frames to test that chance).

If set to 0, the ranged enemy doesn't pursue.

The line that controls running away can be found on that Minotaur Necro file:

    chance_flee=25

That means this enemy quickly reacts to the target being too close, and is likely to run away.

Maybe each creature having some tiny chance of both pursuing and fleeing would help with predictability.

**Comment by DoKel** [comment]
The thing is, ideally, ranged enemies *has* to follow player, but not closer than range of their attack (because they are evil, and they wanna kill player :D). Is there any way to introduce that behaviour?

**Comment by clintbellanger** [comment]
Try playing with those numbers and seeing what happens. With a tiny chance (like 1) of pursing, and high chance of attacking, then the enemy will usually attack if it can. And when it hasn't been able to attack for a while, eventually it will start to pursue.

**Comment by DoKel** [comment]
Yup, I tried now and that is exactly what I expected -- behaviour of shooters is less predictable, just because they are doing like crazy. After short run out of my range of attack, skeletons just stop and strat attack me with their melee. It's fina enough, in my opinion, but when they can shoot still, but start running on me to let me kill them it looks totally illogical.
Btw, i did not understand what did you mean by "chance of attacking". U were talking about `fleeing` and `pursue` parameters, and I tryed different combinations of them (and also `flee_duration` and `flee_cooldown`).
_____
Also it looks like fleeng does not work while player is not moving. Not sure, if it's supposed to be like that, but that is not logical at all -- I can get close to enemy and just stand. If fleeng did not occur while I was getting close, it won't occur at all, and I will be able to kill enemy without trouble.
It's not showing now, when only mob with fleeing is necro, with 25% chance, but with lower percents, or with pursue != 0, it is looking totaly wrong.

**Comment by clintbellanger** [comment]
The entries that look like:

    power=melee,164,5
    power=ranged,171,3

are activation type, power id, and percent chance. Try turning the ranged power chance way up (e.g. 90), so they are likely to shoot any time they are in range. There may be number combinations that give something like the behavior you want. High chance of ranged attack, high chance of fleeing, low chance of pursuing. 

Really, this Standard Behavior is only meant for the simplest of behaviors types, which work for a lot of regular enemies in action games. It's also the only enemy AI type we have implemented right now. Even though it's the most basic behavior, it still has a long mess of code. I think once someone starts to implement a second behavior model, we'll see which parts can be abstracted out and cleaned up.

**Comment by DoKel** [comment]
Can't find out, there default `threat_range` stat is set. The only mention I can found is in flare-engine/src/StatBlock.cpp: `threat_range(0)`, but it can't be true (I can see, that enemies is attacking me, even if I am not at zero-range). However in /enemies txt files there is no definitions of that stat ._. I'll be happy, if u explain to me more about how it works.
_________
Finally, I got the settings, which is making ranged enemies act like they have to (engine system is really flexible, more than I expected, lol). Here they are:

`
#It cause shooter to come closer, sometimes. Not only if player is out of range, but it's realistic enough --- real shooter would like to come closer, to aim better ;)
chance_pursue=1
#That chance is enough. It can vary, but works nice, as for me
chance_flee= 10
#Just defaults, like necro-minotaur have
flee_duration=3s
flee_cooldown=1s
#With this setting skeletons do shooting from visible area. I was trying different values, and can say, that 10 is surely less than needed (threat_range / 2 is hardcoded in standart-behaviour range, closer than which fleeng enemies can't come to hero. 5 is really small value for shooter) and 20 is surely more than needed (skeletons starts shooting even if u do not see them. also it's hard to catch them. really hard)
threat_range = 15
#However, if player came close enough to skeleton, he will not run forever, and will take fight as a man
melee_range = 5
`

I'd really like that settings to appear at empyrean, not just stay at my local fork)

**Comment by clintbellanger** [comment]
Neat! Thanks for experimenting with this and making notes. Actually I'd like to see those settings AND notes added to the main files, if that's good with you. Also, this would be a great example on a new engine wiki page on BehaviorStandard with settings for a few classic enemy styles.

**Comment by DoKel** [comment]
So, have I to create fork with that lines added to all shooters files and send u a pull request?
(also I think, that, in fact, settings have to be ajusted for different enemies. For example, threat_range have surely be decreased for antlions, cuz running towards each would be hell)

**Comment by dorkster** [comment]
Pull requests are welcome! However, I'll need to do some testing before merging.

**Comment by DoKel** [comment]
Ok. It will take a while for me to do all changes (the longest part is clonning the repo to localhost, lol).
But, anyway, where is default threat_range stat set? Which value is used for mobs, without that setting in txt file? Just wanna know for future.

**Comment by dorkster** [comment]
Sorry, I forgot to mention that. 0 is the default engine value, but the Empyrean enemies inherit data that's set in the fantasycore mod (melee_range is also in these files): https://github.com/clintbellanger/flare-game/tree/master/mods/fantasycore/enemies/base

**Comment by DoKel** [comment]
Nice, ty. If there is such structure, mb I have to do something like ranged_preset.txt in fantasycore/enemies and include it in every file, where it is needed? Or have I just keep editing empyrean/enemies files directly?

**Comment by dorkster** [comment]
You can absolutely do that. Although, I would personally have slightly different settings for each type of enemy so that they're not all the same.
