### ISSUE TITLE
Let Gravebloom appear only after boss has been killed

### ISSUE THREAD

**Issue by DoKel** [clintbellanger/flare-game#519]
I accidentally saw commit ["Only let Owl fig appear after quest has been completed"](https://github.com/clintbellanger/flare-game/commit/1164a9dc0689c0a63074e1a2b95c2082a66e41f3), and remembered, that when player meets first boss at st_maria_3 gravebloom apears there immediately. Also it means, that player can (i did not test that, but it looks like that from glowing_obelsik_1 settings) just take a gravebloom and run out, without fighting boss. Is not that strange?

**Comment by dorkster** [comment]
In that scenario, the door behind the player closes (and the game is saved so the player spawns after the door. And the path forward is blocked by the boss. So yes, the player can grab the Gravebloom, but they can't escape without defeating the boss.

**Comment by DoKel** [comment]
He can't leave *back* but doesn't he really can leave by going forward to obelisk?

I see following in npcs/glowing_obelisk_1.txt:

[dialog]
requires_not_status=emp_main_gravebloom
him=(You touch the obelisk, but nothing happens.)

[dialog]
requires_status=emp_main_gravebloom
unset_status=emp_seagate_door

So, it it looks fro me, like player can leave that place without any fight at all.

**Comment by dorkster** [comment]
The player can't reach the obelisk since it's blocked by the two cursed graves. The graves are destroyed when the boss is defeated.

**Comment by DoKel** [comment]
Oh, ok, didn't see, that they are unkillable.
I wanted to create and outstanding issue for following question, but let it be here, if answer will be that short too: what if player moved into map with boss accidentally, and can't kill boss? It looks like the whole game will be ruined.
I was in situation like this, so I know what I am talking about -- I met Wyvern-with-quill when my paladin was too weak to outfight her fairly, even when i spent all my potions. The solution was to hit and run away, waiting while hp will regenerate. I was killing her for very long time, and was praying her ranged stunning attacks to miss. That does not look like regular gameplay :D
Also, after killing the wyvern way to obelisk-2 is opened. But while I was killing regular minions and grubbing loot, it closed. So I was locked at that damn place, and I had to reboot game, to let wyvern appear again to open way forward. That looks like wrong behaviour  too for me.
Ty for ur answers :)

**Comment by edipox** [comment]
Hi guys! I don't know * exactly * what you are talking about, but just to mention: I've played the game some months ago and I used to teleport avoiding enemies and going through doors that didn't open (because I didn't have the keys) causing some odd behaviors

BTW Congratulations for this amazing game!

**Comment by dorkster** [comment]
@DoKel Well, both boss areas have some normal enemies that can be killed for XP. So the player can level up, albeit slowly, if they can't defeat the boss. The way you described the wyvern battle might not seem like regular gameplay, but I think its reasonable for an ill-equipped player to find another method of defeating tough encounters.

>Also, after killing the wyvern way to obelisk-2 is opened. But while I was killing regular minions and grubbing loot, it closed. So I was locked at that damn place, and I had to reboot game, to let wyvern appear again to open way forward. That looks like wrong behaviour too for me.

That's definitely a bug. I'll look into it.

@edipox

The Empyrean game doesn't give the player a teleport ability, so we don't have to worry about them teleporting where they can't go.

**Comment by DoKel** [comment]
And  so why can't we just let player appear backside of door after fight, and open way to boos, so player can choose to fight boss again, or to go and farm some more?.. It's usually made like that in games, as I can remember.

**Comment by dorkster** [comment]
Okay, I fixed the bug where the trap on `maps/temple_of_mez_3.txt` could be triggered after defeating Mez.

I've also made it so that if you defeat a boss and exit the game, you will be warped to the map's entrance when you reload instead of the trapped arena. That way you can go back and farm.
