### ISSUE TITLE
Bug with Fort Nasu's doors

### ISSUE THREAD

**Issue by DoKel** [clintbellanger/flare-game#521]
While playing, I did right sequence of switches to open second-stage doors, but they did not open. However, ability to use switches were disabled after that, and quest of opening last fort nasu door had been added.
That bug surely does not occur every time, because, when I was playing my first cheacter-warrior, I had no problems with the quest.

If it matters, there was no sound of door open too. Can't remember any other special details about that situation.

![screenshot from 2016-09-15 17-49-33](https://cloud.githubusercontent.com/assets/3186111/18554530/33fa5880-7b6d-11e6-90e8-bbfd4091ccd2.png)

**Comment by dorkster** [comment]
I've been unable to reproduce this. Does it persist after reloading the game? If so, can you post/email me your save file?

**Comment by DoKel** [comment]
Yes, I tried to reboot, it persists. Surely, I can post a save file, if u wil tell me, where to find it ._. 
I use Arch Linux, and I installed flare by yaourt with everything default.

**Comment by dorkster** [comment]
On Linux, saves are located in `~/.local/share/flare/saves/`

**Comment by DoKel** [comment]
So here it is: http://pastebin.com/NRKuTjJC

**Comment by DoKel** [comment]
Oh, I've been wrong, that's third stage doors, surely. However, u can see it on the screenshot above.

**Comment by dorkster** [comment]
Stange. Even using your save, I have no problem operating the remaining switches. Can you not open the doors in your screenshot?

The doors in your screenshot aren't part of the quest. They simply open a shortcut in the map and are operated with a single switch. I'll re-word the quest text there, since I see why it would be confusing.

**Comment by DoKel** [comment]
._. I feel very stupid now. Yup, I just missed that single switch, and did not mention that opened door at all. Sorry.
