### ISSUE TITLE
Monsters walking in textures

### ISSUE THREAD

**Issue by DoKel** [clintbellanger/flare-game#524]
After adding fleeing to many enemies, some new bug can occur. One is described in pull-request and is about flying enemies are walking into space (and marked as feature, according to fact, the pull-request is merged). Second is following:

![goblin_bug](https://cloud.githubusercontent.com/assets/3186111/18612770/764d857c-7d6b-11e6-8e02-66bc80b8c43d.png)

Sometimes, enemies can run into textures out of player. I had problem to screenshot situation, when goblin is part-visible, but you can trust me -- he really can walk into the cave ;)

**Comment by dorkster** [comment]
Slightly related: https://github.com/clintbellanger/flare-engine/issues/1279

Thankfully, this can be fixed in this case. The cave tiles can be made solid and the trigger for changing maps can be extended out.
