### ISSUE TITLE
The stun effect of Zombies is f%*^#ing annoying

### ISSUE THREAD

**Issue by libregametester** [clintbellanger/flare-game#525]
In the Empyrean campaign there are Bloodthirsty Zombies level 5 which have a stun effect attack which prevents you from any action for a short duration. They can launch this attack as many times as they want, so if they manage to stun you once, that's it, you can't do anything, just let the game run until you die. If you have good resistance and fast regeneration, it can take a while, maybe it can even block the game indefinitely. Besides, it's not easy to differentiate those bastards from regular zombies before they run at you.

I would suggest to at least balance them by making the stun effect duration at least 1 second shorter than the regeneration of the corresponding attack, so you could do something between two stun (like a warcry), but I'm not a game designer. All I know is that the current behavior makes the game uncool.

**Comment by dorkster** [comment]
The Bloodthirsty Zombie doesn't have any attack that could be mistaken for a stun, so I think you mean the Iceclaw Zombie, which is also level 5. The Iceclaw Zombie's special attack only prevents the player from moving (movement speed set to 0). The player can still attack in this scenario, which means they can kill the zombie to free themselves.

The spells in the game that actually stun the player (e.g. they can't even attack) have a duration of 1 second and a cooldown of 5 seconds from time of casting. This leaves the player with 4 seconds to escape before they can get stunned again by the same enemy.

I hope this clears things up.

**Comment by libregametester** [comment]
In the Blackmire Mines, right out of the teleporter, there are some bloodthirsty zombies level 5 and they have an attack where they hit the floor with their foot, it makes a big noise, pushes the player 1~2 meters away unless he's against an obstacle, and the player can't do any action. This attack seems to have a cooldown of 1 or 1.5 second but definitely not 5. And now I'm at a point where I regen faster than I lose health so I'm stuck.

**Comment by dorkster** [comment]
Something is definitely wrong here. What you're describing is the "quake" spell, which has an ID of 179. None of the level 5 creatures have this spell (the second comma-separated value is the spell ID):
```
lvl5_antlion_freezer.txt:power=melee,164,10
lvl5_antlion_freezer.txt:power=ranged,172,50
lvl5_antlion.txt:power=melee,164,2
lvl5_antlion.txt:power=melee,168,5
lvl5_frozen_corpse.txt:power=melee,164,2
lvl5_frozen_corpse.txt:power=melee,175,10
lvl5_goblin_hurler.txt:power=melee,164,10
lvl5_goblin_hurler.txt:power=ranged,165,50
lvl5_goblin_vanguard.txt:power=melee,164,5
lvl5_skeleton_frostsword.txt:power=melee,180,10
lvl5_summon_zombie.txt:power=melee,164,10
lvl5_summon_zombie.txt:power=melee,168,5
```

And even if one of them *did* have the spell, the cooldown is definitely 5 seconds (from `mods/empyrean_campaign/powers/categories/enemy.txt`):
```
# quake
[power]
id=179
# ...snip...
post_effect=stun,0,1s
cooldown=5s
# ...snip...
```

Do you by chance have any other mods enabled? Ideally, you should only have `fantasycore` and `empyrean_campaign` enabled for the standard experience.

**Comment by DoKel** [comment]
When I saw the topic name, I thought, that it may be my just-for-local-test settings, where I actually enabled quake for a kind of zombie. I do not think, that it was really something of level 5, btw. And I checked actual state of branch, there seems to be no enemies with misenabled quake spell.

But maybe (just maybe) the settings leaked somehow, and topic starter downloaded them before they were fixed?..

If no side mods, which can cause that behaviour, enabled, try to update the game. Or send us ur settings  (Jacobs can tell where to find them, if u don't know)

**Comment by libregametester** [comment]
dorkster, I have fantasycore, empyrean_campaign, and alpha_demo enabled and maybe the problem comes from the alpha_demo. In mods/alpha_demo/enemies/zombie_bloodthirsty.txt there is : 

 cooldown=500ms

So, I'll try to deactivate alpha_demo.

**Comment by dorkster** [comment]
That must be it, since the alpha_demo bloodthirsty zombie uses spell ID 36, which is mapped to the hero's Quake ability in empyrean_campaign.

**Comment by libregametester** [comment]
I made it at Temple of Mez and indeed, that was the alpha_demo mod that caused the problem :)

**Comment by libregametester** [comment]
Where does the campaign stop at the moment ? Black Oak City ?

**Comment by dorkster** [comment]
Yes, there are no more maps at the moment.

**Comment by libregametester** [comment]
well I've forgot to visit Fort Nasu in the meantime. I'm stuck in the room with the 8 switches, is there any hint about how they should be put ?

**Comment by dorkster** [comment]
If you haven't already, take note of the floor tiles in the rooms you've completed. The last room is a bit different. My hint here is to look at the room south of the switch room.

**Comment by libregametester** [comment]
Found it ! Thanks !

**Comment by dorkster** [comment]
Great!

By the way, I recommend starting a new save to see what the early parts of the game are like without alpha_demo enabled. I'm sure there was more than just the zombie that was messed up because of it.
