### ISSUE TITLE
paths (seem to be) wrong in mods/****/maps for [tilesets] for flare-game  v0.20

### ISSUE THREAD

**Issue by scsijon** [clintbellanger/flare-game#528]
picked up both when starting flare-game and devlab from a console and also trying to user the trainer flare devlab with tiled it's giving an error pointing to the paths being wrong.

also some of the mentioned .png files are just not there in the images directory.

**Comment by dorkster** [comment]
How did you acquire flare-game? If you downloaded the zip from Github, the `tiled/` directory is not included. You'll need to pull the whole repository to get everything:

    git clone https://github.com/clintbellanger/flare-game.git

**Comment by scsijon** [comment]
Got it from the code page, thought everything came down, apparently not, will try again and see what happens this time.

**Comment by scsijon** [comment]
Ok downloaded via git again, setup as per instructions.

two problems
1/ flare-game/mods is missing mods.txt, seems a copy is needed here, engine was built with default settings.

2/ now getting error:
ERROR: FontEngine: Unable to determine default font!
and game won't start.

over to you..

copied tiled directory across to the old flare-game-0.20 and it starts

**Comment by dorkster** [comment]
1. mods.txt is provided in flare-engine in the mods/ directory
2. my guess is that you're missing the `default` mod from flare-engine

The instructions [here](https://github.com/clintbellanger/flare-engine/blob/master/INSTALL.engine.md#clone-build-and-play) might help you make sure everything is in the right place.

**Comment by scsijon** [comment]
No, links are there and correct, as per the instructions.

Also flare-engine/mods/mods.txt doesn't seem to be being used?
I've re git'd and rebuilt and re linked and still getting the need to copy it across to get it to work. 

The second error is appearing if I try to load devlab instead of alphademo.

And I know about the tiled directory, I've built and installed tiled, that's my next project.

**Comment by dorkster** [comment]
>Also flare-engine/mods/mods.txt doesn't seem to be being used?

That file is only used the first time the game is run. Your mod configuration is then saved to `~/.config/flare/mods.txt`, which then engine will load when the game is run again.

>The second error is appearing if I try to load devlab instead of alphademo.

So alpha_demo works for you? That would be strange, since devlab *depends* on alpha_demo.

**Comment by scsijon** [comment]
will try soon, back online in about six hours

**Comment by scsijon** [comment]
strange, if I don't select alpha_demo and just devlab, i'm now getting a message in my console that it's loading it anyway and it works.

as far as flare-engine/mods/mods.txt, it seems to want it available, even if it's no longer using it, I tried removing it and it complained in the console.

since the origonal problem is fixed (maybe a note in the readme to let others know the /tiled is not in the zip is worth it), do you wnat to close this issue.

and many thanks for the help.
