### ISSUE TITLE
problems when starting flare-game 0.20 by console

### ISSUE THREAD

**Issue by scsijon** [clintbellanger/flare-game#529]
getting error messages in console when starting flare from the console.

Errors are:

ERROR: Settings: save_prefix not found in engine/misc.txt, setting to 'default'. This may cause save file conflicts between games that have no save_prefix.

ERROR: Settings: virtual_height is undefined. Setting it to 800.

ERROR: [./mods/fantasycore/engine/elements.txt:3] Settings: 'description' is not a valid key.
ERROR: [./mods/fantasycore/engine/elements.txt:7] Settings: 'description' is not a valid key.
ERROR: [./mods/fantasycore/engine/equip_flags.txt:5] Settings: 'description' is not a valid key.
ERROR: [./mods/fantasycore/engine/equip_flags.txt:9] Settings: 'description' is not a valid key.
ERROR: [./mods/fantasycore/engine/equip_flags.txt:13] Settings: 'description' is not a valid key.
ERROR: [./mods/fantasycore/engine/equip_flags.txt:17] Settings: 'description' is not a valid key.
ERROR: [./mods/fantasycore/engine/equip_flags.txt:21] Settings: 'description' is not a valid key.
ERROR: [./mods/fantasycore/engine/equip_flags.txt:25] Settings: 'description' is not a valid key.

can i also have some guidance if you want these in the future as separate issues or will one do when they are from  a common source point such as these are coming from the starting flare from a console.

**Comment by dorkster** [comment]
>ERROR: Settings: save_prefix not found in engine/misc.txt, setting to 'default'. This may cause save file conflicts between games that have no save_prefix.

Which mods do you have enabled? This message is likely safe to ignore.

>ERROR: Settings: virtual_height is undefined. Setting it to 800.

Did you change `MIN_SCREEN_H` in the engine source? Nonetheless, it's safe to ignore this one.

>ERROR: [./mods/fantasycore/engine/elements.txt:3] Settings: 'description' is not a valid key.
>...

If you're using the latest git HEAD of the engine, then you should also be using the latest git HEAD of the game data.

Don't worry about submitting these as one issue. If anything big gets reported in such as fashion, we can always break it off into its own issue.

**Comment by scsijon** [comment]
Yup, engine and game are both 0.20 so i'll leave open for now. 

Redownloading flare-game as some of it apparently didn't git down.

I will see what happens then as there are a 'few' in-game errors also appearing that I haven't yet mentioned.

**Comment by scsijon** [comment]
After a re-git download of both the engine and game, rebuild and reinstall. the error messages now look like warnings rather than actual problems so for now i'll close this one and run on the other issue
