### ISSUE TITLE
Request for 0.3x design? - First Person Viewing

### ISSUE THREAD

**Issue by scsijon** [clintbellanger/flare-game#530]
Idea for 0.3x series?

I was wondering how much work it would be to the engine to have it  be able to work in first person display mode as well as the third person as is at present?

A mapped key or mouse button to swap between. 

It would of course make the mapmakers have to be a little more dilligent in making maps but the game would be a lot more exciting and feel more mainstream than at present. Running through tunnels  and having ceilings in buildings working and the like would really be impressive when in first person mode .

**Comment by clintbellanger** [comment]
This is a 2D game. There is no 3D information to show in first person.
