### ISSUE TITLE
Skeletons spawn in unreacheable area -- Wizard Tower 1

### ISSUE THREAD

**Issue by DoKel** [clintbellanger/flare-game#534]
![bug1](https://cloud.githubusercontent.com/assets/3186111/26027693/1f3fd9f4-381b-11e7-9b52-702aecd8105e.png)

Do not mind strange look of skeletons and other stuff -- it's my changes, and the bug occurs even without them (i just weren't be so lucky to do screenshot on vanilla version).

However, player still can kill the skeletons -- u have to stay rly close to wall and just attack them with some ranged ability.

**Comment by dorkster** [comment]
Was missing a few collision tiles. Fixed now.
