### ISSUE TITLE
Skeleton Archer use seismic attacks instead of bow

### ISSUE THREAD

**Issue by sang-froid** [clintbellanger/flare-game#538]
- Context : I play Empyrean campaign. I am in the Santa Maria's levels. I see an Archer skeleton. He is away from me. He attacks me.
- Expectation : He uses its long range attack (bow).
- Observation : He doesn't use its long range attack. He uses a short range attack (seism).

****VIVE** FLARE !!!!!!!**

**Comment by dorkster** [comment]
Make sure you have the `alpha_demo` mod disabled. Your mod list should look like this:
```
fantasycore
empyrean_campaign
```

Explanation: `alpha_demo` has a level 3 Skeletal Archer enemy that is *not* supposed to be in `empyrean_campaign`. Its attack power is ID 34, which happens to be a level of the player's Quake power (aka the seismic attack).
