### ISSUE TITLE
Krolan is present on the map after you kill him

### ISSUE THREAD

**Issue by igorko** [clintbellanger/flare-game#542]
Go to Krolan map, kill him, do not open chest, leave map and go back. He is present again. Don't know maybe he is not spawned when you open the chest, but he should not be spawned at all after you kill him.

**Comment by dorkster** [comment]
All bosses/mini-bosses respawn intentionally. Each one has a piece of unique gear with a low drop rate, so the player can fight them multiple times to obtain those items.
