### ISSUE TITLE
Missing Map file

### ISSUE THREAD

**Issue by scottfurry** [clintbellanger/flare-game#560]
mod empyrean_campaign
map level Wizard's Tower: Research Chambers( maps/wizards_tower_2.txt ) has artwork and event triggers for access to Wizard's Tower: Laboratory( maps/wizards_tower_3.txt ). During game play, access to Laboratory failed. Discovered map file maps/wizards_tower_3.txt was missing.

**Comment by dorkster** [comment]
This is intentional. The Laboratory map is planned as the next map. The intermap event is there just so I don't have to remember to add it later.

**Comment by niteraleph** [comment]
How do I proceed if I can't go there?
