### ISSUE TITLE
Bug of freeze at Japanese mode

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#561]
In Japanese language mode, the computer freezes when displaying a specific message.
For example, the computer freezes with the message of the critical rate display("Critical Hit Chance") on the status screen (Hot key "C" screen). And the computer freezes when Martigan's message (at "Ah, you are the adventurer?" Scene) at first quest right after starting the game .

Though in Chinese language mode, the same scene will not freeze computer. Therefore probably this bug seems to be a bug peculiar to the Japanese version.

At next message, freezing is happened.

/flare-game

#: ../npcs/martigan.txt:15
msgid "Ah, you're the adventurer? If you seek out danger you're in the right place. We had two guards stationed here; both were recalled to Ancelot. Now we're vulnerable."
msgstr "ああ、あなたは冒険家か？ あなたが危険を探し出す場合は、適切な場所です。我々はかつて、ここに2人の駐留ガードを持っていた; 両者ともアンセロトに招集された。 今、我々は脆弱です。"

#: ../powers/categories/warrior.txt:65 ../powers/powers.txt:192
msgid "Cleave"
msgstr "なぎ払い"

/flare-engine

#: ../../../src/Stats.cpp:76
msgid "Critical Hit Chance"
msgstr "クリティカルヒットのチャンス"

**Comment by dorkster** [comment]
This was an engine bug where trying to render empty strings caused the crash. It should be fixed with https://github.com/clintbellanger/flare-engine/commit/25bf6c3fdbc70dc907229c73a30e1089c6fc41d6.
