### ISSUE TITLE
At Japanese language mode, Some message is not appeared.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#564]
At Japanese language mode, Some message is not appeared.
For example, at martigan chat of first quest,

#: ../npcs/martigan.txt:15
msgid "Ah, you're the adventurer? If you seek out danger you're in the right place. We had two guards stationed here; both were recalled to Ancelot. Now we're vulnerable."
msgstr "ああ、あなたは冒険家か？ あなたが危険を探し出す場合は、適切な場所です。我々はかつて、ここに2人の駐留ガードを持っていた; 両者ともアンセロトに招集された。 今、我々は脆弱です。"

The mesage "あなたが危険を探し出す場合は、適切な場所です。我々はかつて、ここに2人の駐留ガードを持っていた; " is not appeared. (not displayed on the screen.)

Therefore So that , it is displayed such as 
"ああ、あなたは冒険家か？

両者ともアンセロトに招集された。 今、我々は脆弱です。" .

At another case, at log of quest message,

#: ../quests/mineshaft_longsword.txt:4
msgid "Find and defeat the Reanimated Skeleton in Mineshaft Longsword."
msgstr "鉱山 Longsword で アニメートされたスケルトンを見つけ、 倒してください。"

The message "アニメートされたスケルトンを見つけ、 " is not appered.
Therefore So , it is displayed such as 
"鉱山 Longsword で 

 倒してください。"  .

At another case, at second quest message,

#: ../npcs/martigan.txt:22
msgid "We're having problems. Goblins. All the noise from our mining is drawing their attention. We can't have them thinking we're easy prey."
msgstr "我々は問題を抱えている。 ゴブリンたちだ。 私たちの採掘からすべての音は彼らの注目を集めている。 我々を格好の餌食だと考え、 それらを持つことができません。"

The message "私たちの採掘からすべての音は彼らの注目を集めている。" is not appeared.

Therefore , it is displayed such as 
"我々は問題を抱えている。 ゴブリンたちだ。

我々を格好の餌食だと考え、 それらを持つことができません。" .

**Comment by dorkster** [comment]
I suspect this has something to do with how we do word wrapping. We assume that the pixel size of a word is less than the width of its given area, and that words are split by spaces. Japanese breaks these assumptions, but I could also see a very long word made of Latin characters doing the same.

**Comment by dorkster** [comment]
This is now fixed on the engine side: https://github.com/clintbellanger/flare-engine/commit/f76dcdb735cf60cc82f8966403bd3d37b31a1c5f

It also appears to have fixed #567 as I suspected, so I will close both issues.
