### ISSUE TITLE
White wind 's south destination mark (used to unknown destination?) is forgotten about erasing.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#565]

**Comment by dorkster** [comment]
To be clear, are you referring to these?:

![screenshot_2017-11-14_10-31-08](https://user-images.githubusercontent.com/913982/32788371-0a2dcb82-c927-11e7-89b7-54c008eef783.png)

**Comment by sujiniku** [comment]
Yes, I  refer these.

**Comment by dorkster** [comment]
For some reason, I recalled this being normal for alpha_demo maps where potential expansion points were located. Turns out I was wrong, so I removed the arrows in White Wind.
