### ISSUE TITLE
Bug of automatically equiping "Miner's Gloves" ?

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#566]
The item "Miner's Gloves" (reanimated skelton's drop item) is automatically equiped to hands  when get this at first cave (at Mineshaft Longsword). 

Not only at Japanese mode ,but also at English mode, Miner's Gloves  is automatically equiped to hands.

**Comment by dorkster** [comment]
This is intentional. If an item can fit into an empty equipment slot, it is automatically equipped. You can turn of this functionality in the Configuration menu:

![screenshot_2017-11-14_10-25-50](https://user-images.githubusercontent.com/913982/32788158-784e29a0-c926-11e7-98f3-55912a2a6d59.png)
