### ISSUE TITLE
Protrusion message bug at Japanese

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#567]
For example, at the message

#: ../npcs/martigan.txt:77
msgid "I saw no signs of goblins through the locked iron grate door."
msgstr "閉じられた鉄の格子のドアごしに見ましたが、まったくゴブリンの存在はありませんでした。"

The last "た。" is nothing. (Perhaps, "た。" is out of window.)
Therefore, this message is such as "閉じられた鉄の格子のドアごしに見ましたが、まったくゴブリンの存在はありませんでし"  on game.

Another example,

#: ../quests/frontier.txt:10
msgid "River Encampment cleared. Return to Martigan for your reward."
msgstr "川の野営はクリア。 あなたの報酬のためにマーティガンに戻ります。"

The "戻ります" is nothing on screen.
Therefore, the "川の野営はクリア。 あなたの報酬のためにマーティガンに" is appeared.

**Comment by dorkster** [comment]
Resolved: https://github.com/clintbellanger/flare-game/issues/564#issuecomment-344665871
