### ISSUE TITLE
Credits shown is long time. Need of the exit button. 

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#569]
The credit screen of game opening main manu is long time. Once the player open the credits screen, it will not close for about 20 seconds.
If a person who plays this game for the first time opens this credits page, there is anxiety that long this screen may frustrate the player . 

Therefore I think that I should add the exit button from credits. It is a button which can end the credit screen and return to main screnn by pressing the exit button even while credit is being shown.

**Comment by dorkster** [comment]
Pressing Escape will exit the credits screen. However, this isn't obvious if you haven't looked at the keybindings.

I think a good solution would be to add a "next" button, much like the one used for in game dialog.

**Comment by dorkster** [comment]
Implemented in https://github.com/clintbellanger/flare-engine/commit/7fbf82d316a5ae0f3d86578f973cb02390ab8b2f
