### ISSUE TITLE
Bug of no able teleport returning to back from Avergurad's that treasure chest because of monsters

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#575]
![screenshot from 2017-11-19 14-08-55](https://user-images.githubusercontent.com/26195610/32987604-d7b43c20-cd33-11e7-927a-b009c2c32934.png)

It seems that if there are monsters at the teleport destination, it is impossible to teleport.

At the case such as this picture , if player has no bow or no atacking magic, then this player cannot defeat the enemys, therefore player cannot return to back destination.

**Comment by sujiniku** [comment]
I think that, as a prevention method of this bug, for example, ias a condition of teleport acquisition, t is required to player with learning of attacking magic. 

Or, adding a warp zone that the player comes back from the treasure chest side.

**Comment by dorkster** [comment]
The problem with creating a warp zone is that the warp destination could end up blocked, too. The solution I came up with was to have a bridge appear when the player lands on the island. That way, they can leave no matter what.

![screenshot_2017-11-19_12-06-56](https://user-images.githubusercontent.com/913982/32993203-884b42fc-cd22-11e7-94dc-b844806a4654.png)
