### ISSUE TITLE
In Japanese mode, blank lines will appear at the beginning of some item's popup on the status screen.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#580]
![screenshot from 2017-11-22 20-13-01](https://user-images.githubusercontent.com/26195610/33125012-69df7ae8-cfc2-11e7-96af-a40c6c74a66e.png)

![screenshot from 2017-11-22 20-13-40](https://user-images.githubusercontent.com/26195610/33125025-718d0260-cfc2-11e7-8383-0c97633dcd79.png)

![screenshot from 2017-11-22 20-14-09](https://user-images.githubusercontent.com/26195610/33125045-7d72b304-cfc2-11e7-9811-ed9f77b42d42.png)

**Comment by sujiniku** [comment]
![screenshot from 2017-11-22 20-58-33](https://user-images.githubusercontent.com/26195610/33126490-0b1ad948-cfc8-11e7-85d2-75b1fb8bcd9e.png)

Similarly in some chat, a blank line has occurred at the beginning of message.

**Comment by dorkster** [comment]
This has been fixed with the following commit: https://github.com/clintbellanger/flare-engine/commit/fb9f89a3489355f6e4a8f63d3bcd4bb0e8a65511
