### ISSUE TITLE
Can't go past second map of magician (the archives or something like that)

### ISSUE THREAD

**Issue by niteraleph** [clintbellanger/flare-game#582]
In the map with the portal to the underworld, I cannot go through to the next area (game shows brief "unknown destination and does nothing). I know I can't go through the portal yet, but why I can't go to the wizards tower (and fight him)?

**Comment by DS28** [comment]
>  I cannot go through to the next area (game shows brief "unknown destination and does nothing)
Yep, right here:
![_image](https://user-images.githubusercontent.com/13565834/33613489-5690bdf4-da07-11e7-90d9-c264b6a09e8a.png)
