### ISSUE TITLE
explosion quest message is long.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#599]
In living_bones cave, there are quests to break pillars using explosives,
about message "Run! You don't want to be caught in the blast of your own explosion!",
this message is too long.

While reading the message, the hero will be caught in an explosion and dead. Should be shorter this message.
Such as "Explosive! Run away! ".

In a language that has not been translated, it is displayed in English. While the player read English sentences, I do not want to let the player Game-over, so please make it as short as possible.

Or should change the this quest's system so that a warning message is displayed before setting the explosive.

**Comment by dorkster** [comment]
The player is never actually in danger in this scenario. The explosion is only triggered when the player enters one of three zones that are all out of range of the explosion (highlighted below):

![screenshot_2017-12-14_18-01-06](https://user-images.githubusercontent.com/913982/34018767-81303f0a-e0f9-11e7-86ce-41b008289e4e.png)

**Comment by sujiniku** [comment]
Additionaly, I have a question. What does "Run" mean in the message("Run! You don't want to be caught in the blast of your own explosion!") ? "Run" has various meanings. There is also meaning to execute. There is also meaning to "run" against walking. Translation changes whethr it is executing or non-walking.

**Comment by dorkster** [comment]
"Run!" in this context is an instruction to the player to move quickly.
