### ISSUE TITLE
at Fort Nasu switch system, the hint of lamp position.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#609]
![1111111111](https://user-images.githubusercontent.com/26195610/34233866-0bfee326-e62b-11e7-9585-b4695c564127.png)

At Fort Nasu, Perhaps, is the position of this lamp incorrect?

**Comment by dorkster** [comment]
The wall lamps are not related to the switch puzzle, so there's nothing wrong with this lamp.

The solution is actually in the room to the south-west.
