### ISSUE TITLE
I am in trouble at translation of "Averguard Tome" quest.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#615]
I am in trouble because I do not understand the meaning of the explanation of "Averguard Tome" quest (sentence "This tome bears the seal of the Averguard"), therefore I can not translate it. The current Japanese translation is temporary translation.

Is "Averguard Tome" makes the seal of  Burial Chamber?
Or "Averguard Tome" is a key for breaking of  Burial Chamber's seal such as Langlier's Talisman?

at sentence "This tome bears the seal of the Averguard",
What is the meaning of this "seal"? What is the"bears"?

**Comment by dorkster** [comment]
The verb to "bear" in this context means to visibly display a mark or feature. The feature in this case is the "seal", which means an emblem or a symbol.

**Comment by sujiniku** [comment]
Where is the emblem's place in this book? Is it (the place of emblem) the front cover?
 The translation in Japanese depends on where the emblem is.

**Comment by dorkster** [comment]
Yes, it's the front cover.
