### ISSUE TITLE
How is release schedule's policy?

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#620]
A lot of updates are done in 2016, but it was not released.
It should make that players have the latest version play as possible.

Also if the period of not being release is lengthened, there is a risk of misunderstanding that the flare project was canceled.

I think that it should periodically release as much as possible. For example, once per year.

**Comment by dorkster** [comment]
The next release should be in about 3 months. I've written about this here: https://github.com/clintbellanger/flare-engine/issues/1549#issuecomment-355635387

**Comment by sujiniku** [comment]
Releasing 1.0 means that the alpha release will end, is not it?
In case, we need change the name of "alpha_demo" mods to another name.

Otherwise (i.e. as long as keeping "alpha_demo" name), the user misunderstood that "this mods are not updated" and the user is confused.

**Comment by dorkster** [comment]
I don't think we need to change the name of alpha_demo. It signifies that it was content designed during Flare's alpha period. If we renamed it as just demo_game or similar, people might accidentally think it's new content.

It shouldn't matter to much either way, as we won't be shipping the alpha_demo in the various ZIPs. We'll likely only have fantasycore and empyrean_campaign in those packages. And of course, everything will still be in this git repository for people that want them.
