### ISSUE TITLE
Mac binary crashing at launch

### ISSUE THREAD

**Issue by Fr3d-P** [clintbellanger/flare-game#622]
Included crash report , it seems that libfreetype.6.dylib isn't found

[Process-               Flare.txt](https://github.com/clintbellanger/flare-game/files/1594880/Process-.Flare.txt)

**Comment by apocarteres** [comment]
@Fr3d-P this is working engine (with no game itself) http://files.ruads.org/flare_osx.tar.gz for OSX. Please check it out

**Comment by dorkster** [comment]
This thread on the forums may be relevant: https://opengameart.org/forumtopic/mac-version-not-working

**Comment by apocarteres** [comment]
just double checked. The build i made for @Fr3d-P still works on latest OSX.
<img width="1426" alt="screen shot 2018-02-18 at 9 56 42 am" src="https://user-images.githubusercontent.com/3305624/36349197-3491be72-1492-11e8-8242-82cbac05a5f6.png">

**Comment by apocarteres** [comment]
also please use OSX Flare build from today with latest changes:  http://files.ruads.org/flare-osx-18.02.2018.tar.gz

**Comment by tvleavitt** [comment]
This seems to be an artifact of the pre-built 0.19 release version, especially based on the opengameart thread, so it would seem likely that we can close this issue at this point, as we have made a pre-built version available via the web site.
