### ISSUE TITLE
What does "redemption" means which Guill said ?

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#623]
At alpha_demo,

at below message,
#: ../npcs/guill.txt:128
msgid "My worst fear is come alive. Just as with the Warden and with Professor Langlier, Sir Evan Maddox himself was inflicted with undeath. If we are to reclaim the Keep, you must defeat him. The Order will reward you magnificently for this service. But be prepared -- not even undeath will limit Maddox's zeal. Enter the Burial Chamber and allow him redemption."

I do not understand the meaning of "redemption" and I can not translate it.
So what is Guill asking for?
Is Guill asking to kill Maddox? Or Is Guill asking to investigate Burial Chamber?
Or Is Guill asking to return Maddox to heaven?

What is Guill worrying about ?

**Comment by sujiniku** [comment]
I have another question. Also the following sentences, I did not understand the meaning well.

#: ../npcs/guill.txt:142
msgid "You have risked much for the Order. Take this final reward, as your mission here is complete. The grip of necromancy over Averguard Keep is broken -- in time the remaining undead will pass over into death."

Does this meaning that  Guill is going to kill Undead?
Also, there is "necromancy" in the sentence, but are there any relationships with Apprentice Necromancer"?

**Comment by dorkster** [comment]
>#: ../npcs/guill.txt:128

"Redemption" in this case means to return Maddox to the afterlife by killing him. Something like heaven is appropriate, since redemption usually means absolving of sin.

>#: ../npcs/guill.txt:142

"Necromancy" is used as a generic term for the practice of raising the dead. So because the player ended the practicing of necromancy, the undead that were raised from it will go back to being dead.

**Comment by sujiniku** [comment]
Is the grip broken after the player has defeated Maddox?
Or is it no longer broken?

**Comment by dorkster** [comment]
The grip is broken after Maddox is defeated.

**Comment by sujiniku** [comment]
At my understanding, the meaning that Guill says is that the grip is broken at the point just after defeating Maddox, but "the undead will die sometime" means?

If that was the case, after the death of Maddox, I think that it means that the grip will be restored at future, but "At now (just after defeatng Maddox) , the grip is yet broken"?   Do I misunderstood?

**Comment by dorkster** [comment]
Think of the grip of necromancy as a spell. When it's broken, the effect it has on the undead will weaken over time. Eventually, the undead will "die" by returning to their dead state.

**Comment by sujiniku** [comment]
Why did this sentence choose  "grip of necromancy" instead of "grip of necrosis"?
I think that a necromancy breaks the necrosis law at the natural world.

**Comment by sujiniku** [comment]
I'm sorry, but I have another question.

#: ../npcs/guill.txt:79
msgid "I have the prison key. The old prison warden carried it on his person -- he was infected, haunting the depths of the Prison."

What is "infected" in this sentence?
Is "infected" about undeadnization in now? Or is "infected"  about that Averguard's people falling down with plague centuries ago?

**Comment by dorkster** [comment]
Necromancy breaks the law of necrosis. If there was a "grip of necrosis", it would imply that the inhabitants of Averguard were living and then killed by Maddox. A "grip of necromancy" means that the inhabitants were dead and were made to "live" (actually undead) by Maddox.

I didn't write the Averguard quest, but I think the plague is the vessel for the "undeadnization". In other words, they are the same thing. "Infected" makes the most sense in reference to a plague, so I would connect them in that way.

**Comment by sujiniku** [comment]
#: ../npcs/guill.txt:128
 msgid "My worst fear is come alive. Just as with the Warden and with Professor Langlier, Sir Evan Maddox himself was inflicted with undeath. If we are to reclaim the Keep, you must defeat him. The Order will reward you magnificently for this service. But be prepared -- not even undeath will limit Maddox's zeal. Enter the Burial Chamber and allow him redemption."

Does the "order" mentioned here mean a request?
Or is it about the level?

And, Guill is saying " The Order will reward you magnificently for this service.", but I do not feel that there is much reward.
Please increase the reward more.

**Comment by dorkster** [comment]
The Order is a group of people, similar to a guild.

As for the reward, I think the current reward (500 xp, 250 gold, 1 mana potion) is suitable. It's one of the largest rewards in the alpha demo. What would you add to make it better? Maybe a piece of gear? Or just more gold (or a gem)?

**Comment by sujiniku** [comment]
At this time (after Maddox defeat), the player are already equipped with many armors, so no longer the player don't need much money.  Even if player buy weapons and armors, he/she can not equip because with not enough physical or defence or offence.

So, I think that it would be more interesting to get valuables (special item) or get more XP. 
And, I think it is better to get XP 1000 or 1500 or 2000.

In case of that XP is 500, it seems like a small amount of money at first sight because there are one less digits.

**Comment by dorkster** [comment]
Sounds fair, I've added a Ruby to the rewards and changed the XP granted to 1000.

**Comment by sujiniku** [comment]
Sorry, What means "spared" which the hero said to Guill?
What does the hero don't know?

#: ../npcs/guill.txt:71
msgid "Why were the undead spared?"

**Comment by dorkster** [comment]
"Spared" in this case means "not harmed". The hero is asking why there are still undead when most of Averguard has been destroyed.
