### ISSUE TITLE
Bug in the first phrase of the sentence in translation

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#632]
In translation, at the beginning of how many sentences, a bug has occurred.

![screenshot from 2018-01-11 13-22-19-2](https://user-images.githubusercontent.com/26195610/34808934-25aea044-f6d5-11e7-8d6d-ea08d057a960.png)

As one of the occurrence conditions, it seems that a bug has occurred when reading the variable at the beginning of the sentence.

![screenshot from 2018-01-11 13-23-06](https://user-images.githubusercontent.com/26195610/34808955-3776c310-f6d5-11e7-8864-7a3717891b65.png)
![screenshot from 2018-01-11 13-32-34-a](https://user-images.githubusercontent.com/26195610/34808963-3e1ee3c8-f6d5-11e7-97a6-4056e385005e.png)
![screenshot from 2018-01-11 13-32-48-a](https://user-images.githubusercontent.com/26195610/34808966-3fa39d38-f6d5-11e7-82f9-586fdb4992e1.png)
![screenshot from 2018-01-11 13-34-22-2](https://user-images.githubusercontent.com/26195610/34808968-42280896-f6d5-11e7-8594-4f3cfa767a75.png)

**Comment by dorkster** [comment]
Should be fixed with https://github.com/clintbellanger/flare-engine/commit/18af334c79aff9b85232bae5e267e0e448317463
