### ISSUE TITLE
"Passive" of Power menu

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#641]
"Passive" of Power menu description is not added to the translation.

We should change the term "passive" to "automatic" and so on.
I know that there is an RPG term "passive skill", but I think it is incorrect term.

If Interpreting the term as it is, it may be misunderstood as skills like reflection attacks such as bouncing an enemy's arrow with a shield or barrier magic. Or, it may be a skill that absorbs enemy's magic attack and recovers the hero's MP.

**Comment by dorkster** [comment]
You should be able to translate this now with: https://github.com/clintbellanger/flare-engine/commit/8cf2d343538fdb2379b34559f8a89df0c0cc10ea

We'll be keeping it as "passive", as it's used in this context as an antonym of "active".
