### ISSUE TITLE
About Worn Note # 3

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#655]
At empyrean_campaign, in mog_caverns, about "Worn Note" instruction,
Is the instruction of Worn Note # 3 wrong?

#: ../books/mog_3.txt:12
msgid "In the pile of bones near the three pillars"

At least I did not know where it instruct.
When I read "three pillars", I imagined the pillar near the location of the "open seucret door" event's pillar.

**Comment by dorkster** [comment]
I see how this could be confusing. I think we can describe the pillars in question as being "submerged" in water, so I'll describe them as such.
