### ISSUE TITLE
Buyback items should be saved.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#656]
When loads saved game, the items on Buyback should not be erased. 
Because, for example, there may be cases where the player's house  is visited by a visitor and the player have to interrupt game play.

Therefore, it is better to adopt a system in which old items gradually disappear, for example, depending on the play time in the game.

However, the game time also passes during the trade.

As a countermeasure, you should prepare a new variable like "Play elapsed point".
The game should remember the number of defeated enemies, the number of opened chests, etc. The game should capture the point as the progress of the game and story.

If the play elapsed point rises by a certain number, it should change that old items of buyback disappear in order.

**Comment by dorkster** [comment]
I don't see a reason why we should just save the entire buyback indefinitely. If we save the buyback, but have it gradually disappear over time, players might think it's a bug. The buyback itself has a finite capacity, where the oldest item is removed if it's full. So we don't have to worry about saving a massive, ever expanding list of items.

Saving the buyback state should probably be a mod-able engine variable. Some games might want to disable buyback saving for gameplay reasons.

**Comment by dorkster** [comment]
We now save the buyback to the player's save file: https://github.com/clintbellanger/flare-engine/commit/081d3764f51544321050e82e940f33ad5f9ff41f
