### ISSUE TITLE
ERROR: Entity: Antlion Larva got stuck at (15, 10) on an invalid tile.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#660]
ERROR: Entity: Antlion Larva got stuck at (15, 10) on an invalid tile. Please report this bug, if you're able to reproduce it!
ERROR: Entity: Antlion Larva got stuck at (28, 24) on an invalid tile. Please report this bug, if you're able to reproduce it!
ERROR: Entity: Antlion Larva got stuck at (28, 24) on an invalid tile. Please report this bug, if you're able to reproduce it!
ERROR: Entity: Antlion Larva got stuck at (55, 48) on an invalid tile. Please report this bug, if you're able to reproduce it!
ERROR: Entity: Antlion Larva got stuck at (55, 49) on an invalid tile. Please report this bug, if you're able to reproduce it!

**Comment by dorkster** [comment]
I've gotten this a few times as well, also with the Antlion Larva. I suspect we're not properly checking collision when spawning in the second antlion, but I'm not sure yet.

**Comment by dorkster** [comment]
Fixed: https://github.com/clintbellanger/flare-engine/commit/bb130820d22bc49b40fa58a3ceba6528e2d535cc
