### ISSUE TITLE
About Fleshband 's commentary

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#661]
#: ../items/categories/level_16_unique.txt:6
msgid "Smooth to the touch, it constricts itself to the wearer's finger like a vice."

In the manufacturing industry, it is to be a cause of the accident to put a finger between vice. 
So, please change the expression to another.

**Comment by sujiniku** [comment]
Perhaps,in Japan, it may be an example of "Poka-yoke".

https://en.wikipedia.org/wiki/Poka-yoke

"finger like a vice"  in Japan is not a negative meaning. Because not putting "finger like a vice"  is too natural for safety in Japan, Japanese people do not put their fingers between vice.
And, on the first place, in Japan there is no vice for ordinary house, so it does not become a kind of idioms.

Just to be sure, I tried the web search in Japanese language, but I can not find idioms and phrases that used vice.

Although vice itself regulates opening and closing by itself, accidents are few,
However, from the usual point of foolproof, in order to eliminate accidents such as automatic machines of similar opening and closing structure, I think that it is desirable to tell attention so as not to put finger between the opening / closing object.

**Comment by dorkster** [comment]
Thanks for explaining. I've changed the wording of the line to omit the word 'vice'.
