### ISSUE TITLE
Buyback items' sequence is able to be chaged.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#664]
Buyback does not allow to change the sequence of items.
But if the player buyback multiple items and sell its items immediately, the player can change the sequence.
In order to eliminate this unnatural problem, Buyback system should increase the price when the hero buys.

**Comment by dorkster** [comment]
The original purpose of the buyback is for when the player accidentally sells something, they can re-buy it without losing money. So increasing the buy price isn't an option. The sequence of items in the buyback stock isn't really that important.
