### ISSUE TITLE
Antillion Death Swam

### ISSUE THREAD

**Issue by scottfurry** [clintbellanger/flare-game#667]
Playing from ongoing save game. Currently in the Underworld Mines(Empyrian Campaign).
At some point, character will be overwhelmed with a constant, and unending, swarm of antillion level 13's.
This is an epic battle that will last for minutes with blood and carcasses of the dead everywhere - but there is no escape (screen shot: https://i.imgur.com/Wy4OoVs.png).

Suspect there is some kind of overflow error occurring here that creates the swarm.
This problem has occurred a couple of times in other parts of the Underworld map stream (underworld, underworld catacombs). I had thought it was an incompatibility of save games (as warned about on the command line). Each time I saved & exited and restarted. No problems...until now.

**Comment by dorkster** [comment]
That screen shot is pretty wild! If you can reproduce this, can you post your log file and save file?
 The log file is at `~/.config/flare/flare_log.txt`, whereas your save file is `~/.local/share/flare/empyrean/$SAVE_SLOT/avatar.txt`.

**Comment by scottfurry** [comment]
I was just looking for those files now...
The log file is pretty banal:
```
### Flare log file

INFO: Flare Beta 0.90.24 (Linux)
INFO: Active mods: default,fantasycore,centered_statbars,alpha_demo,empyrean_campaign
INFO: MessageEngine: Using language 'en'
INFO: InputState: No joysticks were found.
INFO: RenderDevice: Using SDLSoftwareRenderDevice (software, SDL 2, x11)
INFO: RenderDevice: 2 display(s), using display 0 (1920x1080 @ 60hz)
INFO: RenderDevice: Window size is 1280x849
INFO: RenderDevice: Fullscreen=0, Hardward surfaces=1, Vsync=1, Texture Filter=1
INFO: SoundManager: Using SDLSoundManager (SDL2, pulseaudio)
```
Pulling up save game...

**Comment by dorkster** [comment]
At first glance, I think the `alpha_demo` mod is conflicting with `empyrean_campaign`. You should disable the `alpha_demo` mod.

**Comment by scottfurry** [comment]
Save File
[avatar.txt](https://github.com/clintbellanger/flare-game/files/1713861/avatar.txt)

**Comment by dorkster** [comment]
I've pushed a possible fix for this to flare-engine: https://github.com/clintbellanger/flare-engine/commit/e95aeb79cfc4313d3ba8c0caf9fcc23af9f8cc69

Let us know if you encounter this bug again.

**Comment by scottfurry** [comment]
I guess we have concurrent activity... (this occurred before push above)
I edited the save file (yeah, I cheated) to put the character back into hyper space. Loaded up on Reflection scrolls, health and mana potions, and back into the breach...

I came out of hyperspace in the Underground Catacombs. Fought my way out to the Underground. Cleared this level of monsters with problems. I went into the Torture Chamber - solved and exited. Back into Underground level things started to go sideways. I started to get the beginnings of a swarm (https://imgur.com/khVxOLr) but it suddenly stopped. I suspect the swarm of larva didn't have a chance to build up with the death of the parent. I pressed on...

I then found myself on one of the islands in the Underground. It was here shooting across water that I started to get a swarm potential again (https://imgur.com/PTlV8wr). I sat on the island and coaxed the hordes in to their own demise. I was using a piercing shot quite a bit to clear the opposite island until the swarm stopped (https://imgur.com/irxTK5v). Again, I suspect that I killed the parent Antillions somewhere along the way.

I'll have a go with the engine fix and report back if I run into problems.

**Comment by dorkster** [comment]
Ah, I couldn't tell from your original screen shot if you meant the big antlions or the small ones. My engine fix will have no effect on the small ones. On the game data side, I can try setting the `spawn_limit` for the spawning powers. The parent antlion spawns the larva when joining combat. I suspect that there's a bug(?) in the engine that's letting the antlion join combat multiple times.

**Comment by scottfurry** [comment]
I missed that detail...my bad. Sorry. You can see it in the potential swarm photos where there are masses of larvae (https://imgur.com/khVxOLr - legs up lower right corner and https://imgur.com/PTlV8wr - shoreline lower right corner)

**Comment by dorkster** [comment]
Please try with 5f7bab2. It should keep the larva count at 2 per adult.

**Comment by scottfurry** [comment]
Applied the fix above. I did the route of Underground Catacombs, Underground, Torture Chamber and back. No Antillion Death swarms encountered. I think that fixed it.

**Comment by dorkster** [comment]
Awesome! I'll close this now. Feel free to report if it appears again.

**Comment by scottfurry** [comment]
Just an add-on comment...
In the Underground and some Halls of Infinity levels, the possibility of "mini death swarms" are still possible. The unending streams of antillion larvae are not present but there are more than two/parent showing up in some circumstances.

As best as I can determine, this usually occurs when character is engaged in combat with everything for that level(skeleton archer, goblin, antillion, et al) all at once. As suggested earlier, maybe the antillion keeps spawning when switching between attack and waiting to attack. Not sure.

I don't have screen shots for confirmation, but when I see a small horde of legs up larvae at the end of combat I have to wonder if the spawning logic is a little confused. It reminds me of the antillions from alpha_demo where the antillion will spawn six larvae.

**Comment by dorkster** [comment]
I think a good temporary solution would be to set a fairly large `cooldown` for the spawning powers.

Whatever this bug is, it is likely happening the same frame as the parent antlion joins combat. By using a cooldown, at least we won't be able to trigger the power twice on the same frame.
