### ISSUE TITLE
Translation for item requirements not showing up

### ISSUE THREAD

**Issue by GrishaVar** [clintbellanger/flare-game#671]
![screenshot from 2018-02-12 20-14-18](https://user-images.githubusercontent.com/33952698/36114880-9c0bf294-1031-11e8-84ae-a164ef54c049.png)

**Comment by dorkster** [comment]
Those strings are in the engine's language files, and appear to have not been translated for Russian:

Engine: https://github.com/clintbellanger/flare-engine/blob/master/mods/default/languages/engine.ru.po#L621
Data: https://github.com/clintbellanger/flare-engine/blob/master/mods/default/languages/data.ru.po#L31
