### ISSUE TITLE
After recent pull of game and engine empyrean_campaign no longer loads

### ISSUE THREAD

**Issue by GrishaVar** [clintbellanger/flare-game#673]
![screenshot from 2018-02-12 22-44-07](https://user-images.githubusercontent.com/33952698/36121430-6e6469ba-1046-11e8-8788-5fa2a3e93bc6.png)

**Comment by dorkster** [comment]
Try pulling the engine again. It should be version 0.90.30.

**Comment by GrishaVar** [comment]
Both engine and game say `Already up-to-date.`

**Comment by dorkster** [comment]
Ensure your flare-engine HEAD is at https://github.com/clintbellanger/flare-engine/commit/6467c96a4d7834907b8575eb02365bb1ef0ced0b and recompile the engine.

**Comment by GrishaVar** [comment]
Worked, thanks. Didn't realize I'd need to recompile but I guess that makes sense.
