### ISSUE TITLE
Empyrean Campaign maps layout

### ISSUE THREAD

**Issue by scottfurry** [clintbellanger/flare-game#674]
In the `mods/empyrean_campaign/maps/` folder is the following structure:
```
|
|-- [halls_of_infinity] (folder)
|    |-- halls_of_infinity_1.txt
|    |-- maplist.txt
|-- [parallax] (folder)
|-- ... (other campaign maps)
|-- halls_of_infinity.txt
|-- ... (other campaign maps)
```

No other folder structures are used for map storage. I get parallax from context. The `halls_of_infinity` folder and files were added recently but seems out of place.

`halls_of_infinity.txt` references a map file that does not exist (`underworld_stronghold_2.txt`).
Is this an oops or a work-in-progress/place-holder?

**Comment by dorkster** [comment]
Work in progress :)

The Halls of Infinity is a randomized bonus dungeon that will have many maps, hence the need for a separate directory.

The `underworld_stronghold_2.txt` map is where the entrance to this area will be, but it is not implemented yet.

**Comment by scottfurry** [comment]
So, work-in-progress. Thanks for clearing that up.
Apologies for the noise.
