### ISSUE TITLE
skewer trap  of one way in front of Halls of Infinity

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#678]
Because the skewer trap in front of Halls of Infinity is one way, the hero cannot return back .
Therefore the hero will not be able to return to the Perdition harbor until the player clear the game.

**Comment by dorkster** [comment]
1. The timing of the traps in the barracks is a bit slower than in the foyer to allow for traversing in the opposite direction. Here's a demonstration: https://youtu.be/BFUlN7VZ9J0
2. There's a switch later in the level that enables two sets of bypass teleporters, which allow the player to warp passed the traps.
