### ISSUE TITLE
The Windows version installer flare0.95 doesn’t have alpha_demo.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#681]
Please add alpha_demo into windows version installer.

alpha_demo and empyrean are independent and distinct stories.
I think that it is OK to set the default mods to empyrean,
but please don't remove alpha_demo from the installer.

Also, for many players of windows version, it is difficult to adding mods himself/herself.

Also, although it is convenient for Japan, in the free game community of Japan in recent years, the works that can be cleared in a short time are preferred.

**Comment by dorkster** [comment]
I'm not fond of including the alpha_demo with the installer, but I do have an idea. I think it would be a good opportunity to teach players how to install mods.

- We could provide the alpha_demo as a separate zip download. We probably want to do this anyway to have something to link to [this page](http://flarerpg.org/index.php/mods/flare-alpha-demo/) that's not just the Github repo.
- The Windows installer could create a start menu shortcut to the user's mod folder.
- Installing the mod should be as simply as extracting the zip contents to the mod folder, but we could add instructions somewhere if necessary.

**Comment by dorkster** [comment]
The Alpha demo [page's](http://flarerpg.org/index.php/mods/flare-alpha-demo/) download link now points to a stand-alone zip of the alpha_demo mod. The Windows installer adds a start menu shortcut to the user's mods folder, so it is very simple now to open that folder and extract the contents of the alpha_demo zip to it.

**Comment by sujiniku** [comment]
At website, Such as "Download (2.8 MB)", can you write the approximate data size next to "Download" ?
In particular, "Alternate download (includes all of flare-game)" has a large data size (140MB), and it may take time to download.

**Comment by dorkster** [comment]
I've added download sizes to the Downloads page, the individual Mod pages, and the 0.95 blog posts.
