### ISSUE TITLE
When the gameover,  the hero screams two times.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#682]
When the game-over, the hero screams even after the restart. That is, the hero screams two times. 
The message "You are defeted [Return] to continue" will be displayed not only during game over but also after restart. 
The money after restarting is not a half but a quarter. 

flare-version: 0.95 (windows version)
mods: empyrean

**Comment by dorkster** [comment]
Fixed: https://github.com/clintbellanger/flare-engine/commit/14e93cea0a07790d6c2a0f293470326770287e5f
