### ISSUE TITLE
Price rising speed of Potion 

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#683]
In empyrean_campaign, as the level rises, the price of the potion seems to rise,
but in my sense, I feel the rising speed of potion's price is somewhat faster.

At level 1, the price of the potion was 60 gold, But at Level 3, price is 140 gold, though played time is only a few tens of minutes.
For my play today, HP max of level 1 is 200. And in level 3, HP max is 300.

Compared to the rise in HP MAX, the price rises seems to be intense.

I think we should slow down the price rise speed a little.

**Comment by dorkster** [comment]
I've been doing some play testing and completely agree. Trying to purchase even 5 health potions would usually take all of my money early on.

**Comment by dorkster** [comment]
[This](https://github.com/clintbellanger/flare-game/commit/95a20dedcc597b72ae2f7b00eed12f61c687d5ff) should be better.

**Comment by sujiniku** [comment]
Although it became much better,But I still feel that the price rise is still intense.

Indeed as a result of test-play, the price was 20 gold at the start of the game,then, it reached 60 gold at level 3 after 30 minutes from game start.

The price has tripled in only for 30 minutes. To this, many players may feel uncomfortable.

I think that, instead of increasing the price by 20 gold for each level, should raising the price 20 gold for every 3 levels.
