### ISSUE TITLE
In Windows, maltipul starting up flare is possible easily now.

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#684]
In the Windows version, you can start two Flare at the same time.
This is useful for test-play. So, please don't remove this function.
Indeed, when I looked up the price for each level of potion, I started up two flares.

However, for normal players, starting multiple flare at the same time may cause bugs.

So, with default settings, you should avoid starting multiple flare.

**Comment by dorkster** [comment]
I added instance counting to the engine: https://github.com/clintbellanger/flare-engine/commit/5068f3825088ac8ed3a9485b84b5eb95e624e929

If there are other instances, we now pop up a dialog asking if the user really wants to launch another copy of the game.
![screenshot_2018-02-27_00-30-38](https://user-images.githubusercontent.com/913982/36712199-a7499bd2-1b55-11e8-9b17-0d8123c3ed14.png)
