### ISSUE TITLE
Underground dungeon will submerge in the rainy weather

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#687]
About empyrean, I think that it is better not to let it rain in places like underground dungeons like Lochport.
In the real world, rain flows into the basement, underground dungeons will submerge.
Even in the real world, the subway is closed at the entrance waterproof gate at heavy rain and may be closed to traffic.
Game creators should ensure that players do not notice that underground dungeons are unreal.

**Comment by dorkster** [comment]
We don't concern ourselves much with adhering to reality, but there is an explanation for why the dungeons near Lochport don't get flooded. All of the underground maps in that area have pits and floor grates, indicating that these are not the bottom levels. Rain water would theoretically be able to drain through these areas into the inaccessible, flooded areas below.
