### ISSUE TITLE
Feauter request: pause music when minimised/not in focus

### ISSUE THREAD

**Issue by vgaming** [clintbellanger/flare-game#689]
This would be very handy if you take a break from the game to do smth else, yet you do not want to lose current location "progress" (not being reset to location start point).

**Comment by dorkster** [comment]
On mobile devices, we had to pause the game when switching to another app. So I extended that functionality so that the game gets paused & muted when minimized on all platforms: https://github.com/clintbellanger/flare-engine/commit/d79ef8ac458b69bb3bbd33cd6eafd427d087187e

**Comment by vgaming** [comment]
@dorkster confirming the "minimised" fix -- thanks!

The "pause on focus loss" thing doesn't seem to work on my system though.
I think it would make sense, too. What do you think? Would it be easy to do?

**Comment by dorkster** [comment]
I opted not to do anything on focus loss, as I could see that getting annoying during development. I think having this behavior only on window minimize is satisfactory.

It's certainly possible to do something based on window focus. We would watch for SDL_WINDOWEVENT_FOCUS_LOST and SDL_WINDOWEVENT_FOCUS_GAINED events and act accordingly.

**Comment by vgaming** [comment]
@dorkster understood. Well, it's not critical for me either. Thanks for explanations. I think I'm good with as it is now too.
