### ISSUE TITLE
Do not spend mana/health bottle if on full mana/health

### ISSUE THREAD

**Issue by vgaming** [clintbellanger/flare-game#692]
The feature request is to understand when mana/health spending is appropriate, and do not spend it otherwise.

**Comment by vgaming** [comment]
Sounds like a plan.:)

**Comment by dorkster** [comment]
I ended up going for a different syntax, since "requires" and "requires_not" are mutually exclusive in this case. Hopefully from looking at the [commit](https://github.com/clintbellanger/flare-game/commit/10506e2ab6ce533600952e3186630ae08db84128), the usage of `requires_hpmp_state` should be clear.

**Comment by vgaming** [comment]
Thanks!
(Dunno as for then syntax, I'm not as familiar with the engine... yet.)
