### ISSUE TITLE
discussion: map overview?

### ISSUE THREAD

**Issue by vgaming** [clintbellanger/flare-game#693]
I've been playing the game in the recent days and really like it. One part was hard for me though: what's the global map layout, which locations connect where? To overcome this, I've even started documenting all tiles I've visit, and came up with the following picture:

<details/>
  <summary>spoiler</summary>

![graph_orig](https://user-images.githubusercontent.com/33452702/36795080-20a13824-1cb3-11e8-953e-6ded9b86f9a2.png)
</details>

The question is: should we have something like this built-in? A tree-like structure for all places the hero visited (or _any_ hero visited)?

If not, would it be appropriate to put a picture like this somewhere on the wiki?

**Comment by vgaming** [comment]
BTW, I've finally got bored with doing it manually and wrote a script to auto-generate the tree picture. The following script:
```bash
map_dir="${1:-/usr/share/flare/mods/empyrean_campaign/maps}"

for map_full in "$map_dir"/*.txt "$map_dir"/*/*.txt; do
	map="${map_full%.txt}"
	map="${map##*/}"
	for link_full in $(grep 'intermap=' "$map_full"); do
		link="${link_full%.txt*}"
		link="${link##*/}"
		echo "$map -> $link"
	done
#	for npc_full in $(grep 'filename=npcs' "$map_full"); do
#		npc_full="${npc_full##*=}"
#		for link_full in $(grep 'intermap=' "$map_dir/../$npc_full"); do
#			link="${link_full%.txt*}"
#			link="${link##*/}"
#			echo "$map -> $link [label=\"npc\" style=dashed]"
#		done
#	done
done
```
produces the following picture:

<details/>
  <summary>spoiler</summary>

![graph_no_npc](https://user-images.githubusercontent.com/33452702/36795715-ccf22646-1cb4-11e8-9963-d82fb9bb977e.png)

</details>
If you uncomment the lower part of bash script, you will get NPC connections drawn, too. But the resulting picture somewhy doesn't look very nice (IDK why), so I ended up using the alternative with no NPC connections.

**Comment by dorkster** [comment]
I don't think a tree like this should be in-game, but it could be interesting as part of a strategy guide on the wiki. That script is pretty cool. It could be useful to developers when creating a large game to verify connections between certain maps.

Side note: I had no idea you could do spoilers in Github comments!

**Comment by vgaming** [comment]
@dorkster regarding spoilers -- glad to share. I've google/searx-ed out this link some time ago:
https://github.com/dear-github/dear-github/issues/166
```
<details/>
  <summary>summary</summary>

blah-blah-blah

</details>
```
Rarely useful, but nice for sharing a multi-screen-size picture.:)

**Comment by vgaming** [comment]
Regarding the "graph"-like overview: understood. Agree, that sounds like the most reasonable approach. I'll make wiki edits and then close this issue if you don't mind (or close earlier if needed).

**Comment by vgaming** [comment]
Just at the time got used to the map and finished all quests in the default scenario, I wrote a tool to traverse all maps and plot a graph: https://github.com/vgaming/flare_map_traverse

To be honest, the time was spent unwisely as the output is not significantly better than from the old bash script above. I hoped that smart map iteration would improve things (the script goes through maps recursively starting at "spawn.txt"). But it turned out that hyperspace is connected to everything and breaks sorting.

**Comment by vgaming** [comment]
I hope it's an more or less OK wiki page: https://github.com/clintbellanger/flare-game/wiki/Map-visualization-(graphviz)

Closing issue since the "graph" is now documented on the wiki.

**Comment by vgaming** [comment]
BTW, I now understood that I never actually played the "alpha_demo" campaign. It's seemingly unfinished, and it's quite fast to finish if you're good with Flare mechanics, but I still ran my script to visualize the map.

Result: ![alphademo_npc yes_unreachable_yes](https://user-images.githubusercontent.com/33452702/53015760-1b330c80-344c-11e9-9485-2f7e96b2b8ba.jpg)
The script is the same: https://github.com/vgaming/flare_map_traverse

Enjoy!

**Comment by McSinyx** [comment]
Should this be maintained as a part of flare? I mean especially when we have a whole organization for it?

**Comment by vgaming** [comment]
Interesting. I don't mind doing that, if it's in line with what flareteam thinks as well.

**Comment by dorkster** [comment]
We're currently not doing anything with the alpha demo, so I have no objection if someone wants to maintain or expand it. Pull requests welcome.

**Comment by vgaming** [comment]
@dorkster the idea, if I understand it correctly, is to try put this repo: https://github.com/vgaming/flare_map_traverse  under the "flareteam" github organization.

**Comment by dorkster** [comment]
Oh, I completely misread the other posts. I think adding tools like yours to the org is a good idea. I just transferred two of my own tools to the org, so you're welcome to transfer yours as well.

**Comment by vgaming** [comment]
@dorkster tried now, but apparently I can't transfer the repo if I don't have permissions to create repos in the organization. I'm not part of `flareteam`... I wouldn't mind joining though 😊

**Comment by dorkster** [comment]
@vgaming I sent you an invite.

**Comment by vn971** [comment]
@dorkster cool, thanks!
