### ISSUE TITLE
avoid "Permadeath" by using Pause

### ISSUE THREAD

**Issue by vgaming** [clintbellanger/flare-game#695]
Steps:
* start a new game with "Permadeath"
* go to enemies and die
* don't press Return after you die, instead pause the game by minimizing it.
* unminimize game, press "Save and Exit" in the opened pop-up window
* from the Title screen, load your "died" character again

**Comment by vgaming** [comment]
This may possibly be related to the recent change of Pausing the game upon minimising the window.

**Comment by vgaming** [comment]
UPD: same goes with crashing the client. If you do that, you'll save your character, too.

To circumvent this, would it make sense to delete the save slot as soon as hero dies?

**Comment by dorkster** [comment]
Fixed with 38cb45222f734b007909e53815470532a0a4cb4e

**Comment by vgaming** [comment]
@dorkster thanks for the fix!
