### ISSUE TITLE
Summoned zombie attacks dead enemy

### ISSUE THREAD

**Issue by vgaming** [clintbellanger/flare-game#697]
Summoned zombie attacks a dead enemy (Mez level 8).

Steps:
* go to Mez level 8
* kill it
* summon zombie while near the dead Mez

**Comment by vgaming** [comment]
UPD: zombie attacks all kind of dead enemies, not only the Mez guy.

**Comment by dorkster** [comment]
Fixed in https://github.com/clintbellanger/flare-engine/commit/06ce6963e21e5acda3b9e47a47f701328086d26e
