### ISSUE TITLE
Description of thunderstrike is hard to interpret

### ISSUE THREAD

**Issue by gunchleoc** [clintbellanger/flare-game#710]
The following string in the Empyrean campaign is hard to interpret, and should be rephrased. I have seen differing meanings in the translations for it.

> Lightning strikes from the sky with a high chance to crit movement-impaired enemies.

**Comment by dorkster** [comment]
Would either of these be better? Or should it be re-worded more drastically?

>Lightning strikes from the sky with a high chance to critically damage movement-impaired enemies.

>Lightning strikes from the sky with a high chance to critically damage stunned or slowed enemies.

**Comment by gunchleoc** [comment]
I think either of them is fine :)

On an unrelated topic: In order to stay current, should I check for files to translate on the master branch now, or on the current release branch?

**Comment by dorkster** [comment]
Translating on the master branch is the best way to stay up to date. We're starting a string freeze today, and I've added a summary of the strings that need translating to [the post about it](http://flarerpg.org/index.php/2018/03/26/1-01-coming-soon-string-freeze-starting-today/).

**Comment by gunchleoc** [comment]
Thanks for writing about it here, because I would have missed it again. There is no way to subscribe per e-mail to your blog, and I just can't check the homepages of over 20 projects every single day for announcements. Any chance of a mailing list?

Getting this project on a platform like Transifex would also help. In fact, I have set up an unofficial project there for myself just so that I'll notice any string changes. I don't like submitting translations more often than necessary though, because using git on this project's structure adds about 15min time overhead.

**Comment by dorkster** [comment]
We don't have email subscription, but we do have an [RSS feed](http://flarerpg.org/index.php/blog/feed/) (I've added a link to this on the blog sidebar).

**Comment by gunchleoc** [comment]
So, I have to visit the blog every day, or the RSS feed every day... since I nobody else uses RSS for this. Adding the link was a good idea in any case :)

How would you feel about using a translation platform? This would greatly lower the entry bar for translators too, and make it easier for translators to work as a team.

**Comment by dorkster** [comment]
Okay, let's try Transifex and see how that works out:

- https://www.transifex.com/flareorg/flare-engine/
- https://www.transifex.com/flareorg/flare-game/

**Comment by gunchleoc** [comment]
Thanks - I have sent a join request. Let me know if you want help setting up the configuration.
