### ISSUE TITLE
Redesign the last switch puzzle in Fort Nasu

### ISSUE THREAD

**Issue by dorkster** [clintbellanger/flare-game#711]
Easily the number one complaint I've gotten since release is this switch puzzle. When originally designing it, I wanted to take advantage of both rooms, but this ended up piling on too many new rules compared to the previous puzzles in the dungeon. Some possible redesigns include:

- Moving the switches to the floor tile room, or vice versa
- A set of switches and tiles for each room. The tiles will correspond to the switches in the same room.

Both of these involve ditching the "mirrored room" concept, which I think is the center of confusion.

**Comment by tvleavitt** [comment]
I definitely had to "cheat" and look on the forums for help to figure this out... the difficulty escalation vs. previous switch puzzles is very high. I did get stuck on another switch puzzle "the switch is stuck and won't move", but I managed to figure that out, pretty much by accident.

You might be able to better clue people in, if there were a "book" on a stand in both rooms, and if the symbols on the floor stood out more dramatically. Maybe if there were a visual indicator of progress, too, somehow. You don't have to say which of the three switches is in the correct position, but you could say that one out of 4 sets is correct, 2 out of 4 sets, etc.
