### ISSUE TITLE
Waypoint after St Maria Crypt's boss

### ISSUE THREAD

**Issue by Reylak** [clintbellanger/flare-game#720]
After defeating St Maria Crypt's boss, the player reaches a new area, full of even more dangerous monsters. At this point, the player is exhausted but full of gold. However there's no waypoint to Hyperspace in sight.

<details>
<summary>Click to expand</summary>
The player has to explore the whole area and reach the mines. He enters in hope that the waypoint's in there. However, he can also (as I did) have the same hope for the fort that is just on the side of the path. And then he can die there, or worse, die just upon leaving the fort because every mob respawned (see #707); with the sad effect of losing half his gold (which is a hefty sum after clearing a dungeon and defeating a boss).
</details>

Anyway, I suggest adding a waypoint to Hyperspace after St Maria Crypt's boss battle that is at least easier to _find_, if not to reach.

**Comment by dorkster** [comment]
The waypoints are intentionally laid out evenly across the game world in a way that puts a "buffer" around the major encounters. It adds to the challenge and makes it that much more satisfying when the player eventually does come across the next waypoint.

Players with spare gold still have access to traders in Lake Kuuma (after St. Maria) and Nazia Highlands (after Temple of Mez) before they reach the next waypoint.

Moving the Blackmire Mines waypoint closer would throw off the balance we achieved by spacing them fairly evenly. So we won't be changing it.

**Comment by Reylak** [comment]
While I understand how the waypoints are evenly spaced out, I just think that it's frustrating for the player to try his luck exploring a map to find a safe spot. I suggested to move Blackmire's waypoint at least **just outside the entrance of the cave** so it's visible from Lake Kuuma, and even better closer to the beginning of the map. Another option could be to leave hints of the waypoint's direction to avoid wandering around the map risking death. 

Despite the "won't fix" decision, I just wanted to clarify my suggestion, which is to make the waypoint's position more obvious and not to rely on "exploration luck" to quickly find the spot.
