### ISSUE TITLE
Slingshot projectiles invisible in Lake Kuuma and Grot Lagoon

### ISSUE THREAD

**Issue by tvleavitt** [clintbellanger/flare-game#721]
Slingshot projectiles are the same color as the background of these snowy regions, and thus are invisible... I suggest dynamically changing the color of the projectile based on background or some such? Should this be filed here or in flare-engine?

**Comment by dorkster** [comment]
I don't think dynamically changing projectile colors is a particularly valuable feature. It would be much simpler to change the artwork for the slingshot rock (and possibly arrows, too).

In the case of the slingshot art, I think we could try a more grey stone color. To make this visible in the grey dungeon area, it could have some white specular highlighting so there's still some white in there, too.

**Comment by tvleavitt** [comment]
That sounds reasonable. The arrows are hard to view at times, but never totally invisible. I assume that this is because they're larger and a mix of colors.
