### ISSUE TITLE
Trader's mystery to go to ruins to trade

### ISSUE THREAD

**Issue by sujiniku** [clintbellanger/flare-game#722]
In Flare-game, humans doesn't live in town except the first village, and I feel a doubt why the trader(such as abasi, Talrych) needs a journey.

In alpha_demo, it is expected from the name of "Frontier" that many humans live in a developed town other than the frontier place.
So the trader is expected to be moving between those developed towns and the frontier.

However, in empyrean, it is unknown whether there are places where many humans live. It is ruins except the first town.

In the next release, I hope that, in addition to the first town, you should put out the town where living humans live. And, in that town, it should be able to do shopping.

**Comment by dorkster** [comment]
Because humans are few and far between in the Empyrean Campaign, Abasi's traveling isn't for trade routes, but rather for scavenging. This is how he obtains his stock, and it's presumed that his clients consist of the player and the inhabitants of Perdition Harbor.
