### ISSUE TITLE
Warn for duplicate keybindings

### ISSUE THREAD

**Issue by Reylak** [clintbellanger/flare-game#723]
When setting my keybindings from qwerty to azerty, I switched A and Q in the first column, but I did not check the second column. As a result, when moving left using Q (on azerty, WASD is ZQSD) I kept using my item in "bar1" (funny thing is that it was the health pots so at some point I though the game had some sort of auto-use feature).

I think it'd be nice to _warn_ the player that he is binding the same button to two different actions, including from two different columns because both action will be triggered anyway.

**Comment by dorkster** [comment]
We don't test (and thus don't support) binding the same key to multiple actions. So we should make keybindings exclusive. If you assign a key that's already being used, we should unbind the previous bindings.

**Comment by Reylak** [comment]
I understand. While unbinding previous bindings, I think it'd be best to warn the player or highlight the previous, now-unbound binding (at least if it's in the same key set -- I mean, the column in the GUI).

**Comment by dorkster** [comment]
Yes, we can display a small warning when something gets unbound.

**Comment by dorkster** [comment]
Implemented here: https://github.com/clintbellanger/flare-engine/commit/a49d30d9533fb50859035e0a7779129caede656d
