### ISSUE TITLE
Stash is too small

### ISSUE THREAD

**Issue by Arcanister** [clintbellanger/flare-game#725]
There are many items in the game, and space in Stash is too limited, so you cannot use it for example to organize items neatly, such as use one line per item set, one line for all the fire rings, other line for ice rings and so on.

Stash space isn't even enough to collect full sets of rings and artifacts, let alone armors and weapons.

Using traders might be a solution, but it seems that when you sell enough items to the trader, filling their space, old items disappear permanently, also the game does not allow to rearrange items in trader buyback stock. In other games I have used various chests to store excessive items, but in this game you cannot put items in chests other than shared stash.

**Comment by sujiniku** [comment]
I agree. Because Perdition town is less product, for this town, so there is the significance of keeping items.

**Comment by vgaming** [comment]
> also the game does not allow to rearrange items in trader buyback stock
IIRC buyback has 0 cost overhead, so you can just buy back and sell right after. Which would mean re-arranging.

To be honest I think most items and gold are useless because you have too many of these anyway. You collect it at first when you don't know the game yet, but it's evident enough that you don't need that many gold after a few games. If there'd be super-cool weapons you could buy for 100-1000x of current prices, some of it would make sense though.

**Comment by dorkster** [comment]
The stash is double the size of the player's inventory, which should be more than enough. We're not going to change the stash size.

**Comment by Arcanister** [comment]
More than enough for what? It's not enough for purpose I wanted to use it for.
I wanted to keep complete collection of rings and armors with 4 level granularity (such as keep only items of 4th, 8th, 12th and 16th level items).
Perhaps if you only keep special items, such as st. Maria set + Ardwen gloves + Krolan's Hammer, you can reduce amount of slot you need, but it also turns out that they have requirements, so you still would want to keep set of cloth items and weapons of level 3, which would be available for fresh character immediately.

**Comment by dorkster** [comment]
The main purpose of the stash is for sharing items between saves. It's ability to store items is secondary.

Other than the pure collection aspect, there's no point in keeping lower level items. A single level of items consists of 28 items. There are also 28 unique items in the game. So storing all the unique items and an entire set of items for the player's level takes 56/80 available slots.

If you truly want to save everything, I recommend sharing the items with another save file. Chances are, your class/build won't support using every item anyway, so those items are better served to a character than can take advantage of them.

**Comment by vgaming** [comment]
I don't understand all this. Do your messages mean that I should be able to transfer artifacts/items from hero to hero?

Guessing from the name, I thought so too, but it never works for me so I thought it's not possible. The way I test it:
* I create a new character, go to Perdition Harbor, go to "Shared Stash" (in the middle between Hyperspace and Florin), put off my clothes into "Shared Stash"
* Then I create another character, go to the same "Shared Stash" and observe nothing being stored there.

Is it how it's supposed to work? My client is compiled from flare-game version 0eccfe7a2ead7cad9f76dbd5cd9c2ff4a888bddf and flare-engine version e4c7f6533ff96ff42e8899a7db0d3c727ca96f17.

**Comment by vgaming** [comment]
My "saves/empyrean" directory looks like this:
```
~/.local/share/flare/saves/empyrean
├── 1
│   ├── avatar.txt
│   └── stash_HC.txt
├── 2
│   ├── avatar.txt
│   └── stash_HC.txt
├── 3
│   ├── avatar.txt
│   └── stash_HC.txt
└── stash.txt
```

with `stash.txt` always being empty.

**Comment by vgaming** [comment]
// I've updated to the current master on both flare-game and flare-engine, re-compiled, but I still observe "stash" being character-local.

**Comment by dorkster** [comment]
The sharing feature is disabled for permadeath characters. So in your case, the stash is only for storage for a single character.

**Comment by vgaming** [comment]
Indeed the stash works in this case! Awesome!xD
