### ISSUE TITLE
Protection rings seem useless

### ISSUE THREAD

**Issue by Arcanister** [clintbellanger/flare-game#726]
Low level protection rings only reduce damage by 2% or so, which is negligible, if damage of one hit is less than 50, if I understand it correctly, high level rings provide more significant effect, but they cannot be worn by low level characters.  Only highest level rings have some use, but at the time when you get them you are likely to have good armors, which works better. And due to limited space in inventory and stash you can't carry all elemental rings (two of each kind) all the time.

However I could be misinterpreting game mechanic related to those rings.

**Comment by vgaming** [comment]
Indeed. I personally never use any kind of protection rings even. Only item find chance or experience. Or the +250HP in late game.;-)

**Comment by vgaming** [comment]
@Arcanister to be fair, you can theoretically combine a number of those rings or other artifacts to overcome rounding, even if damage is based on natural numbers (I don't know).

But rings themselves seem kinda weak..

**Comment by dorkster** [comment]
I also agree. Perhaps we could try a higher base level bonus, like 10% - 20%.
