### ISSUE TITLE
empyrean_campaign fonts are l10n-unfriendly

### ISSUE THREAD

**Issue by ildar** [clintbellanger/flare-game#737]
e.g. they don't have Cyrillic glyph so in Russian locale the Book of Dead is unreadable
Currently used fonts are:
1. Alex Brush
2. Textura Libera Tenuis X

**Comment by dorkster** [comment]
I've set Liberation Sans as a fallback for where those fonts would be used.

![screenshot_2018-04-18_11-03-48](https://user-images.githubusercontent.com/913982/38940517-46a4b152-42f8-11e8-82c3-4d3c06108fd7.png)

**Comment by ildar** [comment]
Thanks
👍
