### ISSUE TITLE
Bring back Fort Nasu "reflection" puzzle

### ISSUE THREAD

**Issue by AMDmi3** [clintbellanger/flare-game#738]
If I'm not missing anything up, in 1.00 there was a "Reflection" puzzle in the final room Fort Nasu, where you've had to place levers according to symbols in the adjacent room. I've noted to myself that I've got a real pleasure from that puzzle, as it was more complex and interesting than other much more straightforward puzzles in flare. However in 1.02 the map has been changed to a dull lever puzzle. I suggest to bring back original map. Boring puzzles do not benefit the gameplay.

**Comment by dorkster** [comment]
Sorry, but the number of complaints I got about that puzzle far outweighed the number of people that liked it. Since puzzles aren't really the focus of an action RPG like ours, I decided to dumb the puzzle down.
