### ISSUE TITLE
Consider to rename "St.Maria: Prison" to "St.Maria: Catacombs"

### ISSUE THREAD

**Issue by un404known** [clintbellanger/flare-game#744]
Hi there. The crypt in Lochport consists of three levels:

 1. Mausoleum
 2. Prison
 3. Crypt

A prison under a mausoleum right above a crypt with a saint in it does not make much sense. I 'd like to suggest to rename the second level to "St. Maria: Catacombs". The whole level consists of skeletons and monsters you already found at the cemetery. The new name would fit-in nicely into the structure. Style and monster would fit the new name.

**Comment by dorkster** [comment]
Good point. I agree that "Catacombs" is a better fit here.
