### ISSUE TITLE
Reset Powers Button

### ISSUE THREAD

**Issue by vmonteirobr** [clintbellanger/flare-game#748]
Hi guys, i see as good addtion to gameplay if were possible to reset all powers using one button in the GUI, because eventualy the players select erroneurs powers for your avatar, thanks for the good job, that project is incredible. 
After the reset, the player should received all the points to redistribute in powers.

**Comment by dorkster** [comment]
While we won't add a dedicated button for this, we'll likely add an NPC or an item to do this. Using this method would prevent the player from abusing the ability to change powers on the fly.

The functionality for resetting powers is already in the engine and can be executed through an event or the developer console. You can try it by [enabling developer mode](https://github.com/clintbellanger/flare-game/wiki/Enabling-Developer-Mode) and entering `exec respec=powers`. The documentation for `respec` is as follows:

```
event.respec | ["xp", "stats", "powers"], bool : Respec mode, Ignore class defaults | Resets various aspects of the character’s progression. Resetting “xp” also resets “stats”. Resetting “stats” also resets “powers”.
```

**Comment by dorkster** [comment]
>I raquested to include Brazilian Porguguese language in translation project, i pretend to translate all the main campain.

I assume Portuguese and Brazilian Portuguese aren't interchangeable? If that's true, I'll accept the request and also add it to the flare-engine project.

**Comment by vmonteirobr** [comment]
Thanks, yes thats true, two Portuguese not interchangeable, are similar but not same.
That translation project improve all the atmospheric of the main campain easing to Brazilian public.

**Comment by dorkster** [comment]
@vmonteirobr Thanks. I've pulled in the work you've done so far. Don't forget that the engine translation files are also [on Transifex](https://www.transifex.com/flareorg/flare-engine/).
