### ISSUE TITLE
Character class names in power dialog and start screen

### ISSUE THREAD

**Issue by un404known** [clintbellanger/flare-game#751]
When you create a new character / load a existing game you get the following character class names:

 * Brute
 * Adept
 * Scout

However, the power dialogue uses the following tab labels:

 * Warrior
 * Ranger
 * Magician

**Comment by dorkster** [comment]
This is intentional. While there are obvious parallels between the character classes and the power trees, they are not directly connected. A Brute may dip into the Ranger power tree for Haste or Wolf's Eye, or a "battlemage" Adept may want to utilize War Cry in the Warrior tree.
