### ISSUE TITLE
Set system language by default

### ISSUE THREAD

**Issue by Wuzzy2** [clintbellanger/flare-game#755]
If the game starts the first time, the default language should be the system language. If the system language cannot be determined, fall back to English.

In the language selection in the settings, there should also be an entry called “System language” so the user can choose to either select a language explicitly or just use the system's default.

What I have just suggested is standard practice in pretty much any game with translations, so Flare should do it, too.

**Comment by dorkster** [comment]
This issue was raised a long time ago on the engine repo: https://github.com/clintbellanger/flare-engine/issues/581
