### ISSUE TITLE
When starting new game, select random portrait and maybe class

### ISSUE THREAD

**Issue by Wuzzy2** [clintbellanger/flare-game#756]
For a bit more variety, I suggest that whenever you start a new game, make Flare pre-select a random portrait+name and class.
So that multiple savegames don't being dominated by the default character. :wink:

Mods should be able to disable random pre-selection of portrait and/or class, in case the default selection actually matters to the mod maker.

**Comment by dorkster** [comment]
Not a bad idea. I've previously had many "Delrek"s while testing :)

**Comment by dorkster** [comment]
We can now initially pick both a random portrait and a random class. I've also added a "Randomize" button, so the player can re-roll both the portrait and class.

- https://github.com/clintbellanger/flare-engine/commit/6833eb03ca6f7a6478465605ca50c398f5ea348c
- https://github.com/clintbellanger/flare-engine/commit/04e53725e7b9ea609d38aebb677ea7a77e831f1b
- https://github.com/clintbellanger/flare-game/commit/9451a5c09303c9b7e592b3ec47bc2312e608e761
