### ISSUE TITLE
Cursed grave becomes “Dead”

### ISSUE THREAD

**Issue by Wuzzy2** [clintbellanger/flare-game#757]
If you destroy a cursed grave, it will be “Dead”. This word is shown at the health bar at the top.
This is the wrong word, it should be something like “Destroyed” for the cursed grave or other non-living objects.

**Comment by dorkster** [comment]
Fixing this would definitely happen on the engine side. So I'll close this and we can just use https://github.com/clintbellanger/flare-engine/issues/1656 for discussion.
