### ISSUE TITLE
Add sounds for attacking and destroying cursed grave

### ISSUE THREAD

**Issue by Wuzzy2** [clintbellanger/flare-game#758]
The cursed grave is a bit odd, it does not seem to make any sounds when attacking or destroying it. Either that, or the sounds are so silent, I can't hear them.
Anyway, cursed grave should have sounds for getting hit and getting destroyed, it's odd that it doesn't have any so far.

In any case, I think the cursed grave should have proper sounds. I like to hear the cursed grave crumbling down into pieces. :)

**Comment by Danimal696** [comment]
You will need to cut them, but i think these could work:
https://opengameart.org/content/mining-pick
https://opengameart.org/content/falling-rock

**Comment by dorkster** [comment]
Implemented in https://github.com/clintbellanger/flare-game/commit/86027bbe46ede66d24b526ee2518d8bb56f4cb7e

Here's a demo video: https://youtu.be/9to8w5CHWyw
