### ISSUE TITLE
Empyrean Campaign: Flipped arrows in Black Oak City

### ISSUE THREAD

**Issue by Wuzzy2** [clintbellanger/flare-game#760]
Some arrows at the map border in the Black Oak City map are flipped and go the wrong way.

These are the arrows at the bottom of the map.

The arrows at the other end of the map are OK.

**Comment by dorkster** [comment]
Black Oak City looks fine. I think you meant Black Oak *Farm*, which does in fact have incorrect arrows.

**Comment by Wuzzy2** [comment]
Oops!
This is correct.
