### ISSUE TITLE
Empyrean Campaign: Name is not written into Book of the Dead

### ISSUE THREAD

**Issue by Wuzzy2** [clintbellanger/flare-game#761]
If you look into the Book of the Dead after you have written your name into it, the book still does not contain your name. :-(

How to reproduce this bug:
* Play Empyrean Campaign in Flare 1.06
* Get all the required items to write the name into the book
* Click the book stand to write
* Wait for the animation to finish
* Click on book stand again → book interface opens

Expected result:
You see your name in the book.

Actual result:
Book still looks exactly as before.

**Comment by dorkster** [comment]
We'll have to make it so that book text can get the player's name. This functionality exists for dialog text, so it shouldn't be difficult to apply it here.
