### ISSUE TITLE
Martigan quest dialogue typo

### ISSUE THREAD

**Issue by Nikolice** [clintbellanger/flare-game#764]
In a quest dialogue about un-dead friends of a merchant (Martigan?) – is a word printed two times, instead of one (I played a localized version, but the dialogue seemed to remain being English): „… them … them …“ – or similar.

**Comment by dorkster** [comment]
I believe this was fixed for English with https://github.com/clintbellanger/flare-game/commit/89a1cb5eb02bffc760f5ab28b5f20e84ad9318be. So maybe the translation hasn't been updated for this. Which language are you using?

**Comment by Nikolice** [comment]
Yes, exactly: it is! … Thank you.
I – use belorussian; and currently – I am translating: all the texts… Should I „fork“ it here, on GitHub? (I guess: yes, I should.)

**Comment by dorkster** [comment]
Yes, we accept translations on Github. We're also on [Transifex](https://www.transifex.com/flareorg), if that's preferred for you.
