### ISSUE TITLE
Is there a roadmap?

### ISSUE THREAD

**Issue by nitramr** [clintbellanger/flare-game#767]
Hi all, 
I could not find any roadmap which gives some information about new planned features, milestones or project state. Is there anything? The blog just show what is already done, but not what is planned.

regards,
Martin

**Comment by dorkster** [comment]
We have milestones for 1.07: [engine](https://github.com/clintbellanger/flare-engine/milestone/6), [game](https://github.com/clintbellanger/flare-game/milestone/4)

There's also [this thread](https://github.com/clintbellanger/flare-game/issues/739) for discussion about new game content, but there's no concrete time frame there.

**Comment by brigazvi** [comment]
Now I've created [one](https://github.com/clintbellanger/flare-game/wiki/roadmap).
@dorkster , you are welcome to post your long-term plans.

**Comment by dorkster** [comment]
@brigazvi Thanks. I added what I've been working on now (large engine cleanup) as it doesn't have an issue open on Github. I also added a few longer term goals. These may shift around in regards to which version they'll land in, but it should give a rough idea.

**Comment by nitramr** [comment]
Very cool, thanks. I think we can close that issue.
