### ISSUE TITLE
A 'fireball' flies towards the mouse, even when I play with the keyboard

### ISSUE THREAD

**Issue by brigazvi** [clintbellanger/flare-game#770]
![asda](https://user-images.githubusercontent.com/37640970/42275624-8f28a95a-7f99-11e8-9cb3-938d0c69bb4b.gif)

It also happened to me with 'blood strike'.

**Comment by dorkster** [comment]
Make sure that "Mouse aim" is unchecked in the Input configuration:

![screenshot_2018-07-04_09-53-13](https://user-images.githubusercontent.com/913982/42281116-9aced8de-7f70-11e8-923f-12cf22a6aa04.png)
